///
///Это автоматически сгенерированный класс!
///Не редактируйте его вручную!
///Все внесённые исземения могут быть утеряны!
///
///Этот клас сгенерирован вспомагательной программой "ResourcesClassGenerator".
///Для генерации этого класса должна быть запущена указанная выше программа.
///
public sealed class LocalizedStrings
{
    public static string current_languade { get; private set; }
    public static string loading { get; private set; }
    public static string level_generading { get; private set; }
    public static string resoures_loadind { get; private set; }
    public static string play_game { get; private set; }
    public static string settings { get; private set; }
    public static string squad { get; private set; }
    public static string training { get; private set; }
    public static string developers { get; private set; }
    public static string understud { get; private set; }
    public static string healtarget_weakest { get; private set; }
    public static string healtarget_strongest { get; private set; }
    public static string healtarget_all { get; private set; }
    public static string first_phase { get; private set; }
    public static string second_phase { get; private set; }
    public static string two_phases_skill { get; private set; }
    public static string error { get; private set; }
    public static string missing_string { get; private set; }
    public static string formation_ranks_name { get; private set; }
    public static string formation_ranks_description { get; private set; }
    public static string formation_phalanx_name { get; private set; }
    public static string formation_phalanx_description { get; private set; }
    public static string formation_shields_name { get; private set; }
    public static string formation_shields_description { get; private set; }
    public static string condition_inFight_name { get; private set; }
    public static string condition_inFight_description { get; private set; }
    public static string terrain_modifier_dirt_name { get; private set; }
    public static string terrain_modifier_dirt_description { get; private set; }
    public static string terrain_modifier_forest_name { get; private set; }
    public static string terrain_modifier_forest_description { get; private set; }
    public static string terrain_modifier_forest_light_name { get; private set; }
    public static string terrain_modifier_forest_light_description { get; private set; }
    public static string terrain_modifier_grass_name { get; private set; }
    public static string terrain_modifier_grass_description { get; private set; }
    public static string terrain_modifier_road_ground_name { get; private set; }
    public static string terrain_modifier_road_ground_description { get; private set; }
    public static string terrain_modifier_road_rock_name { get; private set; }
    public static string terrain_modifier_road_rock_description { get; private set; }
    public static string terrain_modifier_water_light_name { get; private set; }
    public static string terrain_modifier_water_light_description { get; private set; }
    public static string health { get; private set; }
    public static string squadHealth { get; private set; }
    public static string armour { get; private set; }
    public static string baseDamage { get; private set; }
    public static string armourDamage { get; private set; }
    public static string attack { get; private set; }
    public static string defence { get; private set; }
    public static string defenceHalfSector { get; private set; }
    public static string missileBlock { get; private set; }
    public static string attackDistance { get; private set; }
    public static string speed { get; private set; }
    public static string acceleration { get; private set; }
    public static string rotationSpeed { get; private set; }
    public static string chargeImpact { get; private set; }
    public static string chargeDeflect { get; private set; }
    public static string chargeDamage { get; private set; }
    public static string defenceGoingThrough { get; private set; }
    public static string flyingSpeed { get; private set; }
    public static string weight { get; private set; }
    public static string weapon_damage { get; private set; }
    public static string armour_armour { get; private set; }
    public static string missile_block_short { get; private set; }
    public static string squad_info_main { get; private set; }
    public static string skills { get; private set; }
    public static string consumables { get; private set; }
    public static string squad_info_main_stats { get; private set; }
    public static string weight_very_light { get; private set; }
    public static string weight_light { get; private set; }
    public static string weight_medium { get; private set; }
    public static string weight_heavy { get; private set; }
    public static string weight_very_heavy { get; private set; }
    public static string arrowWalley_radius { get; private set; }
    public static string arrowWalley_arrowscount { get; private set; }
    public static string cooldown { get; private set; }
    public static string duration { get; private set; }
    public static string cost { get; private set; }
    public static string mass { get; private set; }
    public static string weaponConstraint_cantReformPhalanx { get; private set; }
    public static string weaponConstraint_cantReformPhalanxInFight { get; private set; }
    public static string weaponConstraint_cantUseShield { get; private set; }
    public static string attention { get; private set; }
    public static string yes { get; private set; }
    public static string no { get; private set; }
    public static string ok { get; private set; }
    public static string cancel { get; private set; }
    public static string upgrade { get; private set; }
    public static string gold { get; private set; }
    public static string silver { get; private set; }
    public static string expirience { get; private set; }
    public static string name { get; private set; }
    public static string description { get; private set; }
    public static string equipment { get; private set; }
    public static string inventory { get; private set; }
    public static string equipment_market { get; private set; }
    public static string consumables_market { get; private set; }
    public static string equipment_ground { get; private set; }
    public static string you_died { get; private set; }
    public static string how_to_use { get; private set; }
    public static string executable_use_type_click { get; private set; }
    public static string executable_use_type_drag_drop_place { get; private set; }
    public static string executable_use_type_drag_direction { get; private set; }
    public static string equipment_body_chainmail_name { get; private set; }
    public static string equipment_body_chainmail_description { get; private set; }
    public static string equipment_body_linotorax_name { get; private set; }
    public static string equipment_body_linotorax_description { get; private set; }
    public static string equipment_body_anatomic_armour_name { get; private set; }
    public static string equipment_body_anatomic_armour_description { get; private set; }
    public static string equipment_body_lorica_segmentata_name { get; private set; }
    public static string equipment_body_lorica_segmentata_description { get; private set; }
    public static string equipment_body_none_name { get; private set; }
    public static string equipment_body_none_description { get; private set; }
    public static string equipment_helmet_corinthian_close_name { get; private set; }
    public static string equipment_helmet_corinthian_close_description { get; private set; }
    public static string equipment_helmet_thrace_open_name { get; private set; }
    public static string equipment_helmet_thrace_open_description { get; private set; }
    public static string equipment_helmet_none_name { get; private set; }
    public static string equipment_helmet_none_description { get; private set; }
    public static string equipment_shield_hoplon_name { get; private set; }
    public static string equipment_shield_hoplon_description { get; private set; }
    public static string equipment_shield_bakler_name { get; private set; }
    public static string equipment_shield_bakler_description { get; private set; }
    public static string equipment_shield_scutum_name { get; private set; }
    public static string equipment_shield_scutum_description { get; private set; }
    public static string equipment_shield_thyreos_name { get; private set; }
    public static string equipment_shield_thyreos_description { get; private set; }
    public static string equipment_shield_none_name { get; private set; }
    public static string equipment_shield_none_description { get; private set; }
    public static string equipment_weapon_doru_name { get; private set; }
    public static string equipment_weapon_doru_description { get; private set; }
    public static string equipment_weapon_sharp_doru_name { get; private set; }
    public static string equipment_weapon_sharp_doru_description { get; private set; }
    public static string equipment_weapon_kopis_name { get; private set; }
    public static string equipment_weapon_kopis_description { get; private set; }
    public static string equipment_weapon_ksifos_name { get; private set; }
    public static string equipment_weapon_ksifos_description { get; private set; }
    public static string equipment_weapon_sarrisa_name { get; private set; }
    public static string equipment_weapon_sarrisa_description { get; private set; }
    public static string equipment_weapon_wings_sarrisa_name { get; private set; }
    public static string equipment_weapon_wings_sarrisa_description { get; private set; }
    public static string skill_arrowWalley_name { get; private set; }
    public static string skill_arrowWalley_description { get; private set; }
    public static string skill_charge_name { get; private set; }
    public static string skill_charge_description { get; private set; }
    public static string skill_phalanx_push_name { get; private set; }
    public static string skill_phalanx_push_description { get; private set; }
    public static string skill_shield_bash_name { get; private set; }
    public static string skill_shield_bash_description { get; private set; }
    public static string consumable_pilums_name { get; private set; }
    public static string consumable_pilums_description { get; private set; }
    public static string consumable_pilums_light_name { get; private set; }
    public static string consumable_pilums_light_description { get; private set; }
    public static string consumable_pilums_heavy_name { get; private set; }
    public static string consumable_pilums_heavy_description { get; private set; }
    public static string consumable_pilums_perfect_name { get; private set; }
    public static string consumable_pilums_perfect_description { get; private set; }
    public static string skill_upgrade_arrowWalley_startunlock_name { get; private set; }
    public static string skill_upgrade_arrowWalley_startunlock_description { get; private set; }
    public static string skill_upgrade_arrowWalley_basedamage_largebow_name { get; private set; }
    public static string skill_upgrade_arrowWalley_basedamage_largebow_description { get; private set; }
    public static string skill_upgrade_arrowWalley_basedamage_weightarrows_name { get; private set; }
    public static string skill_upgrade_arrowWalley_basedamage_weightarrows_description { get; private set; }
    public static string skill_upgrade_arrowWalley_armourdamage_sharparrows_name { get; private set; }
    public static string skill_upgrade_arrowWalley_armourdamage_sharparrows_description { get; private set; }
    public static string skill_upgrade_arrowWalley_armourdamage_temperedarrows_name { get; private set; }
    public static string skill_upgrade_arrowWalley_armourdamage_temperedarrows_description { get; private set; }
    public static string skill_upgrade_arrowWalley_arrowscount_name { get; private set; }
    public static string skill_upgrade_arrowWalley_arrowscount_description { get; private set; }
    public static string skill_upgrade_arrowWalley_radius_name { get; private set; }
    public static string skill_upgrade_arrowWalley_radius_description { get; private set; }
    public static string skill_upgrade_arrowWalley_radius_minus_name { get; private set; }
    public static string skill_upgrade_arrowWalley_radius_minus_description { get; private set; }
    public static string skill_upgrade_arrowWalley_cooldown_name { get; private set; }
    public static string skill_upgrade_arrowWalley_cooldown_description { get; private set; }
    public static string skill_upgrade_charge_startunlock_name { get; private set; }
    public static string skill_upgrade_charge_startunlock_description { get; private set; }
    public static string skill_upgrade_charge_speed_moretrain_name { get; private set; }
    public static string skill_upgrade_charge_speed_moretrain_description { get; private set; }
    public static string skill_upgrade_charge_speed_ligthfootwear_name { get; private set; }
    public static string skill_upgrade_charge_speed_ligthfootwear_description { get; private set; }
    public static string skill_upgrade_charge_speed_shortranderun_name { get; private set; }
    public static string skill_upgrade_charge_speed_shortranderun_description { get; private set; }
    public static string skill_upgrade_charge_duration_longrangerun_name { get; private set; }
    public static string skill_upgrade_charge_duration_longrangerun_description { get; private set; }
    public static string skill_upgrade_charge_acceleration_reinforcefootbase_name { get; private set; }
    public static string skill_upgrade_charge_acceleration_reinforcefootbase_description { get; private set; }
    public static string skill_upgrade_charge_acceleration_lowerstart_name { get; private set; }
    public static string skill_upgrade_charge_acceleration_lowerstart_description { get; private set; }
    public static string skill_upgrade_charge_intensivtrain_name { get; private set; }
    public static string skill_upgrade_charge_intensivtrain_description { get; private set; }
    public static string skill_upgrade_charge_damage_runningpunch_name { get; private set; }
    public static string skill_upgrade_charge_damage_runningpunch_description { get; private set; }
    public static string toMainMenu { get; private set; }
    public static string goToMainMenu_header { get; private set; }
    public static string goToMainMenu_info { get; private set; }
    public static string resetSettings_header { get; private set; }
    public static string resetSettings_info { get; private set; }
    public static string currentValue { get; private set; }
    public static string baseValue { get; private set; }
    public static string currentValue_baseValue { get; private set; }
    public static string durability_new { get; private set; }
    public static string durability_worn { get; private set; }
    public static string durability_damaged { get; private set; }
    public static string can_use_in_this_formations { get; private set; }
    public static string toast_cant_use_with_shield { get; private set; }
    public static string toast_cant_use_with_current_weapon { get; private set; }
    public static string toast_not_enough_gold { get; private set; }
    public static string toast_not_enough_silver { get; private set; }
    public static string toast_not_enough_expirience { get; private set; }
    public static string toast_not_enough_equipment_count { get; private set; }
    public static string toast_stat_max_upgrade { get; private set; }
    public static string toast_cant_drop_weapon { get; private set; }
    public static string toast_cant_drop { get; private set; }
    public static string toast_cant_reform_phalanx_with_this_weapon { get; private set; }
    public static string toast_cant_reform_phalanx_in_fight_with_this_weapon { get; private set; }
    public static string toast_cant_reform_shields_without_shields { get; private set; }
    public static string toast_cant_use_skill_in_this_formation { get; private set; }
    public static string toast_cant_use_skill_without_shields { get; private set; }
    public static string toast_cant_use_because_of_cooldown { get; private set; }
    public static string next { get; private set; }
    public static string previous { get; private set; }
    public static string close { get; private set; }
    public static string again { get; private set; }
    public static string button_inv { get; private set; }
    public static string button_tips_review { get; private set; }
    public static string button_formation { get; private set; }
    public static string modyfyers_panel { get; private set; }
    public static string button_minimap { get; private set; }
    public static string inv_used_equip { get; private set; }
    public static string inv_cells_for_store { get; private set; }
    public static string inv_items_on_ground { get; private set; }
    public static string all_tips_review { get; private set; }
    public static string button_squad_panel { get; private set; }
    public static string buttons_skills { get; private set; }
    public static string buttons_consumables { get; private set; }
    public static string tip_try_to_buy_equip_and_consumables { get; private set; }
    public static string tip_try_to_train_squad_and_skills { get; private set; }
    public static string tutorial_tip_death_try_to_follow_the_advices { get; private set; }
    public static string tutorial_tip_lvl1_barricades { get; private set; }
    public static string tutorial_tip_lvl1_basic { get; private set; }
    public static string tutorial_tip_lvl1_how_to_block_arrows { get; private set; }
    public static string tutorial_tip_lvl1_close_inventory { get; private set; }
    public static string tutorial_tip_lvl1_congratulations { get; private set; }
    public static string tutorial_tip_lvl1_drag_equipment { get; private set; }
    public static string tutorial_tip_lvl1_dropped_equipment { get; private set; }
    public static string tutorial_tip_lvl1_form_info_phalanx { get; private set; }
    public static string tutorial_tip_lvl1_form_info_ranks { get; private set; }
    public static string tutorial_tip_lvl1_form_info_shields { get; private set; }
    public static string tutorial_tip_lvl1_go_to_camp_exit { get; private set; }
    public static string tutorial_tip_lvl1_go_level_exit { get; private set; }
    public static string tutorial_tip_lvl1_go_to_point { get; private set; }
    public static string tutorial_tip_lvl1_how_to_open_inventory { get; private set; }
    public static string tutorial_tip_lvl1_minimap_info { get; private set; }
    public static string tutorial_tip_lvl1_minimap_how_to_use { get; private set; }
    public static string tutorial_tip_lvl1_open_inventory { get; private set; }
    public static string tutorial_tip_lvl1_open_minimap { get; private set; }
    public static string tutorial_tip_lvl1_other_formations_dependedn { get; private set; }
    public static string tutorial_tip_lvl1_phalanx_side_movement { get; private set; }
    public static string tutorial_tip_lvl1_read_modifyer_panel { get; private set; }
    public static string tutorial_tip_lvl1_how_to_reform_squad { get; private set; }
    public static string tutorial_tip_lvl1_reform_to_phalanx { get; private set; }
    public static string tutorial_tip_lvl1_reform_to_shields { get; private set; }
    public static string tutorial_tip_lvl1_squad_modifyer_panel { get; private set; }
    public static string tutorial_tip_lvl1_squad_phalanx_movement { get; private set; }
    public static string tutorial_tip_lvl1_squad_ranks_movement { get; private set; }
    public static string tutorial_tip_lvl1_squad_shields_movement { get; private set; }
    public static string tutorial_tip_lvl1_take_a_shields { get; private set; }
    public static string tutorial_tip_lvl1_take_a_spears { get; private set; }
    public static string tutorial_tip_lvl1_watch_equipment_stats { get; private set; }
    public static string tutorial_tip_lvl1_watch_squad_stats { get; private set; }
    public static string tutorial_tip_lvl1_open_squad_modifyer_stats { get; private set; }
    public static string tutorial_tip_lvl1_tutorial_welcome { get; private set; }
    public static string tutorial_tip_lvl2_charge_how_to_use { get; private set; }
    public static string tutorial_tip_lvl2_charge_pikes { get; private set; }
    public static string tutorial_tip_lvl2_congratulations { get; private set; }
    public static string tutorial_tip_lvl2_consumables { get; private set; }
    public static string tutorial_tip_lvl2_destroy_enemy_on_path { get; private set; }
    public static string tutorial_tip_lvl2_destroy_marked_enemy { get; private set; }
    public static string tutorial_tip_lvl2_enemy_pilums { get; private set; }
    public static string tutorial_tip_lvl2_go_to_point_1 { get; private set; }
    public static string tutorial_tip_lvl2_go_to_point_2 { get; private set; }
    public static string tutorial_tip_lvl2_go_to_point_3 { get; private set; }
    public static string tutorial_tip_lvl2_go_to_point_after_fight { get; private set; }
    public static string tutorial_tip_lvl2_go_to_point_exit { get; private set; }
    public static string tutorial_tip_lvl2_how_to_open_squad_main_info_panels { get; private set; }
    public static string tutorial_tip_lvl2_look_to_enemy_end_regroup_to_phalanx { get; private set; }
    public static string tutorial_tip_lvl2_open_squad_main_info_panels { get; private set; }
    public static string tutorial_tip_lvl2_phalanx_defence { get; private set; }
    public static string tutorial_tip_lvl2_pikes { get; private set; }
    public static string tutorial_tip_lvl2_pilums_how_to_use { get; private set; }
    public static string tutorial_tip_lvl2_retreat_and_regroup { get; private set; }
    public static string tutorial_tip_lvl2_shoot_pikes { get; private set; }
    public static string tutorial_tip_lvl2_squadless_unit { get; private set; }
    public static string tutorial_tip_lvl2_squad_main_info_panel_icons { get; private set; }
    public static string tutorial_tip_lvl2_squad_main_info_panels { get; private set; }
    public static string tutorial_tip_lvl2_squad_phalanx_movement { get; private set; }
    public static string tutorial_tip_lvl2_squad_ranks_movement { get; private set; }
    public static string tutorial_tip_lvl2_squad_shields_movement { get; private set; }
    public static string tutorial_tip_lvl2_squad_surround { get; private set; }
    public static string tutorial_tip_lvl2_take_shields_and_attack { get; private set; }
    public static string tutorial_tip_lvl2_take_units { get; private set; }
    public static string tutorial_tip_lvl2_welcome { get; private set; }
    public static string tutorial_tip_lvl3_congratulations { get; private set; }
    public static string tutorial_tip_lvl3_destroy_enemy { get; private set; }
    public static string tutorial_tip_lvl3_forest_be_carefull { get; private set; }
    public static string tutorial_tip_lvl3_go_to_enemy_1 { get; private set; }
    public static string tutorial_tip_lvl3_go_to_exit { get; private set; }
    public static string tutorial_tip_lvl3_go_to_forest { get; private set; }
    public static string tutorial_tip_lvl3_go_to_forest_enemy { get; private set; }
    public static string tutorial_tip_lvl3_go_to_road { get; private set; }
    public static string tutorial_tip_lvl3_take_heavy_equipment { get; private set; }
    public static string tutorial_tip_lvl3_take_units { get; private set; }
    public static string tutorial_tip_lvl3_terrain_base { get; private set; }
    public static string tutorial_tip_lvl3_terrain_forest { get; private set; }
    public static string tutorial_tip_lvl3_terrain_other { get; private set; }
    public static string tutorial_tip_lvl3_terrain_road { get; private set; }
    public static string tutorial_tip_lvl3_terrain_road_heavy { get; private set; }
    public static string tutorial_tip_lvl3_weight_base { get; private set; }
    public static string tutorial_tip_lvl3_welcome { get; private set; }
}
