StatsPanelUI
StatsPanelUI StatsPanelUI.Instance
Referenced by Awake.
Toggle StatsPanelUI.StatsToggle
GameObject StatsPanelUI.statsPanel
new Animation StatsPanelUI.animation
Referenced by Start.
List<string> StatsPanelUI.animNames
Referenced by OnToggle, Start.
string StatsPanelUI.formatNumberPercent
Referenced by OnEquipmentChanged.
string StatsPanelUI.formatNumber
Referenced by OnEquipmentChanged.
string StatsPanelUI.formatConnat
Referenced by OnEquipmentChanged.
string StatsPanelUI.zero
Referenced by OnEquipmentChanged.
void StatsPanelUI.Awake()
References Instance.
void StatsPanelUI.Start()
References animation, animNames, OnEquipmentChanged, OnFormationChanged, OnToggle, RefreshPanel.
void StatsPanelUI.OnDestroy()
References OnEquipmentChanged, OnFormationChanged, Squad.playerSquadInstance.
void StatsPanelUI.OnToggle(bool value)
References animNames.
Referenced by Start.
void StatsPanelUI.OnFormationChanged(FormationStats.Formations formation)
References OnEquipmentChanged.
Referenced by OnDestroy, Start.
void StatsPanelUI.OnEquipmentChanged(Equipment eq)
References Localization.armour, Localization.armourDamage, UnitStats.Attack, Localization.attack, Localization.attackDistance, Localization.baseDamage, UnitStats.Defence, Localization.defence, formatConnat, formatNumber, formatNumberPercent, UnitStats.Health, Localization.health, Localization.missileBlock, Squad.playerSquadInstance, Localization.rotationSpeed, UnitStats.RotationSpeed, Localization.speed, UnitStats.Speed, Squad.UnitCount, Squad.UnitStats, zero.
Referenced by OnDestroy, OnFormationChanged, RefreshPanel, Start.
void StatsPanelUI.RefreshPanel()
References OnEquipmentChanged.
Referenced by Start.