ScoreMarket
ConvertType
ConvertType ScoreMarket.convertFor
Referenced by Converter_OnCliclOk.
NumberConverter ScoreMarket.converter
Referenced by OnDestroy, Start.
void ScoreMarket.Start()
References converter, Converter_OnCliclOk, Gold_OnValueChanged.
void ScoreMarket.OnDestroy()
References converter, Converter_OnCliclOk, Gold_OnValueChanged.
void ScoreMarket.Gold_OnValueChanged(float oldVal, float newVal, DSPlayerScore.Score sender)
Referenced by OnDestroy, Start.
void ScoreMarket.Converter_OnCliclOk()
References convertFor.
Referenced by OnDestroy, Start.