FadeScreen
CanvasGroup FadeScreen.cg
Referenced by Awake, FadeOff, FadeOn.
Action FadeScreen.OnFadeOn
Referenced by Fade, FadeOn, StaticFade.
Action FadeScreen.OnFadeOff
Referenced by Fade, FadeOff, StaticFade.
FadeScreen FadeScreen.Instance
Referenced by Awake.
void FadeScreen.Awake()
References cg, Instance.
void FadeScreen.Start()
References FadeWhenStart.
void FadeScreen.FadeWhenStart()
References FadeOff.
Referenced by Start.
IEnumerator FadeScreen.Fade(float duration, bool fade, CanvasGroup cg)
References OnFadeOff, OnFadeOn.
Referenced by FadeOff, FadeOn.
void FadeScreen.FadeOff(float duration)
References cg, Fade.
Referenced by FadeWhenStart.
void FadeScreen.FadeOn(float duration)
References cg, Fade.
static void FadeScreen.FadeOff(CanvasGroup cg, float duration, MonoBehaviour owner, Action OnFadeOff=null)
References OnFadeOff, StaticFade.
static void FadeScreen.FadeOn(CanvasGroup cg, float duration, MonoBehaviour owner, Action OnFadeOn=null)
References OnFadeOn, StaticFade.
static IEnumerator FadeScreen.StaticFade(float duration, bool fade, CanvasGroup cg, Action OnFadeOn=null, Action OnFadeOff=null)
References OnFadeOff, OnFadeOn.
Referenced by FadeOff, FadeOn.