SquadCerrentProp
CanvasGroup SquadCerrentProp.inFight
Referenced by PlayerSquadInstance_OnInFightFlagChanged, Start.
CanvasGroup SquadCerrentProp.inRanks
CanvasGroup SquadCerrentProp.inPhalanx
CanvasGroup SquadCerrentProp.inShields
Squad SquadCerrentProp.squad
Referenced by OnDestroy, Start.
void SquadCerrentProp.Start()
References Squad.CurrentFormation, HideCG, inFight, Squad.playerSquadInstance, PlayerSquadInstance_OnFormationChanged, PlayerSquadInstance_OnInFightFlagChanged, ShowFormationIco, squad.
void SquadCerrentProp.OnDestroy()
References PlayerSquadInstance_OnFormationChanged, PlayerSquadInstance_OnInFightFlagChanged, squad.
void SquadCerrentProp.PlayerSquadInstance_OnFormationChanged(FormationStats.Formations formation)
References ShowFormationIco.
Referenced by OnDestroy, Start.
void SquadCerrentProp.ShowFormationIco(FormationStats.Formations formation)
Referenced by PlayerSquadInstance_OnFormationChanged, Start.
void SquadCerrentProp.PlayerSquadInstance_OnInFightFlagChanged(bool newValue)
References HideCG, inFight, ShowCG.
Referenced by OnDestroy, Start.
void SquadCerrentProp.ShowCG(CanvasGroup cg)
Referenced by PlayerSquadInstance_OnInFightFlagChanged.
void SquadCerrentProp.HideCG(CanvasGroup cg)
Referenced by PlayerSquadInstance_OnInFightFlagChanged, Start.