NumberPickerDialogBox
TextMeshProUGUI NumberPickerDialogBox.title
Referenced by Show.
TextMeshProUGUI NumberPickerDialogBox.message
Referenced by Show.
TMP_InputField NumberPickerDialogBox.inField
Referenced by OnClickOk.
Button NumberPickerDialogBox.ok
Button NumberPickerDialogBox.cancel
Action<string> NumberPickerDialogBox.onClickOk
Referenced by OnClickOk, Show.
StringBuilder NumberPickerDialogBox.b
Referenced by Awake.
CanvasGroup NumberPickerDialogBox.canvas
Referenced by Awake.
NumberPickerDialogBox NumberPickerDialogBox.Instance
Referenced by Awake.
void NumberPickerDialogBox.Awake()
References b, canvas, Instance.
void NumberPickerDialogBox.Start()
References Hide, OnClickCancel, OnClickOk.
void NumberPickerDialogBox.OnClickOk()
References Hide, inField, onClickOk.
Referenced by Start.
void NumberPickerDialogBox.OnClickCancel()
References Hide.
Referenced by Start.
void NumberPickerDialogBox.Show(string title, string message, Action< string > onClickOk, InputField.ContentType type)
References message, onClickOk, title.
void NumberPickerDialogBox.Hide()
Referenced by OnClickCancel, OnClickOk, Start.