AiSquadController
AiSquadBehaviour
LayerMask AiSquadController.directFindPathLayers
float AiSquadController.distToResetStartPosBeforeFindPath
Ground AiSquadController.ground
Referenced by GoTo, Start.
Squad AiSquadController.squad
Referenced by GoTo, OnDrawGizmos, SetActiveSquad, SetStartPosition, SquadAttack, SquadBehaviour, Start.
Squad AiSquadController.playerSquad
Referenced by Attack, SlowUpdate, Start.
GameObject AiSquadController.squadPositions
Referenced by Start.
GameObject AiSquadController.squadUnits
Referenced by Start.
float AiSquadController.distanceToPlayer
Referenced by ActivateSquad, BehaviorOnAttack, CalcDistances.
float AiSquadController.distanceToStartPosition
Referenced by BehaviorOnDefend, CalcDistances.
float AiSquadController.distPlayerSquadToStartPos
Referenced by BehaviorOnDefend, CalcDistances.
Vector3 AiSquadController.startPosition
Referenced by CalcDistances, OnDrawGizmos, SquadAttack, Start.
bool AiSquadController.attackPlayer
Referenced by BehaviorOnAttack, BehaviorOnDefend, SquadAttack.
bool AiSquadController.pathfindingIsRunning
Referenced by FindPath, GoTo.
List<Vector3> AiSquadController.path
Referenced by FindPath, GoTo.
Vector2 AiSquadController.startFindPath
Referenced by FindPath, GoTo.
Vector2 AiSquadController.endFindPath
Referenced by FindPath, GoTo.
Vector2 AiSquadController.movePosition
Referenced by FindPath, GoTo, SetStartPosition, SquadAttack.
Quaternion AiSquadController.lookRotation
Referenced by FindPath, GoTo, SquadAttack.
bool AiSquadController.canGo
Referenced by GoTo, SquadAttack.
float AiSquadController.slowApdateDeltaTime
Referenced by SlowUpdate.
float AiSquadController.attackDeltaTime
Referenced by Attack.
float AiSquadController.distanceToActivateSquad
Referenced by ActivateSquad, OnDrawGizmos.
float AiSquadController.radiusOfDefendArea
Referenced by BehaviorOnDefend, OnDrawGizmos.
float AiSquadController.radiusOfAttackArea
Referenced by BehaviorOnAttack, BehaviorOnDefend, OnDrawGizmos.
AiSquadBehaviour AiSquadController.mode
Referenced by SquadBehaviour.
void AiSquadController.Start()
References Attack, ground, playerSquad, SlowUpdate, squad, Squad_OnSquadDestroy, squadPositions, squadUnits, startPosition.
void AiSquadController.Squad_OnSquadDestroy()
Referenced by OnDestroy, Start.
void AiSquadController.OnDestroy()
References Squad_OnSquadDestroy.
IEnumerator AiSquadController.SlowUpdate()
References ActivateSquad, CalcDistances, playerSquad, slowApdateDeltaTime, SquadBehaviour.
Referenced by Start.
IEnumerator AiSquadController.Attack()
References attackDeltaTime, playerSquad, SquadAttack.
Referenced by Start.
void AiSquadController.ActivateSquad()
References distanceToActivateSquad, distanceToPlayer, SetActiveSquad.
Referenced by SlowUpdate.
void AiSquadController.CalcDistances()
References distanceToPlayer, distanceToStartPosition, distPlayerSquadToStartPos, startPosition.
Referenced by SlowUpdate.
void AiSquadController.SquadAttack()
References attackPlayer, canGo, GoTo, lookRotation, movePosition, Squad.PositionsTransform, squad, startPosition.
Referenced by Attack.
void AiSquadController.SquadBehaviour()
References BehaviorOnAttack, BehaviorOnDefend, BehaviorOnHold, mode, squad.
Referenced by SlowUpdate.
void AiSquadController.SetActiveSquad(bool newValue)
References squad.
Referenced by ActivateSquad.
void AiSquadController.GoTo()
References MapBlock.BLOCK_SCALE, canGo, Ground.ColCountOfBlocks, endFindPath, FindPath, Ground.Grid, ground, lookRotation, movePosition, path, pathfindingIsRunning, Squad.PositionsTransform, Ground.RowCountOfBlocks, SetStartPosition, squad, startFindPath, MapBlock.WORLD_BLOCK_SIZE.
Referenced by SquadAttack.
void AiSquadController.SetStartPosition()
References Squad.FlipRotation, movePosition, Squad.PositionsTransform, squad.
Referenced by GoTo.
void AiSquadController.FindPath(System.Object o)
References MapBlock.BLOCK_SCALE, endFindPath, lookRotation, movePosition, path, pathfindingIsRunning, startFindPath.
Referenced by GoTo.
void AiSquadController.BehaviorOnHold()
Referenced by SquadBehaviour.
void AiSquadController.BehaviorOnAttack()
References attackPlayer, distanceToPlayer, radiusOfAttackArea.
Referenced by SquadBehaviour.
void AiSquadController.BehaviorOnDefend()
References attackPlayer, distanceToStartPosition, distPlayerSquadToStartPos, radiusOfAttackArea, radiusOfDefendArea.
Referenced by SquadBehaviour.
void AiSquadController.OnDrawGizmos()
References distanceToActivateSquad, radiusOfAttackArea, radiusOfDefendArea, squad, startPosition.