McFileManager
McFileManager McFileManager.Instance
Referenced by Awake.
bool McFileManager.DialogShowed
Referenced by McGrid.DrawGrid.
McHider McFileManager.dialogPanel
InputField McFileManager.dialogPanelText
Transform McFileManager.parentFileList
Referenced by ClearFileList, CreateItem.
GameObject McFileManager.originalItemOfList
Referenced by CreateItem.
McGridConstructController McFileManager.gridConstructController
Referenced by Start.
string [] McFileManager.fnames
Referenced by RefreshFileList.
bool McFileManager.dialogShowed
Referenced by HideDialog, ShowDialogPanel.
XmlSerializer McFileManager.blockSerializer
MapBlock McFileManager.mapBlocks
Referenced by OnOkButtonClick.
const string McFileManager.PATH_TO_GRIDS
Referenced by GeneradeFileName, OnOkButtonClick, RefreshFileList.
const string McFileManager.DIMEN
Referenced by McUiListItem.LoadMapBlock, OnOkButtonClick, RefreshFileList.
void McFileManager.Awake()
References Instance.
void McFileManager.Start()
References gridConstructController, RefreshFileList.
void McFileManager.RefreshFileList()
References ClearFileList, CreateItem, DIMEN, fnames, PATH_TO_GRIDS.
Referenced by OnOkButtonClick, Start.
void McFileManager.CreateItem(string file)
References originalItemOfList, parentFileList.
Referenced by RefreshFileList.
void McFileManager.ClearFileList()
References parentFileList.
Referenced by RefreshFileList.
void McFileManager.HideDialog()
References dialogShowed.
Referenced by OnCancelButtonClick, OnOkButtonClick.
void McFileManager.GeneradeFileName()
References McBlockEntryChooser.BlockEntrance, McExitDirectionChooser.exit, McExitDirectionChooser.hasExit, PATH_TO_GRIDS.
void McFileManager.ShowDialogPanel()
References dialogShowed.
void McFileManager.OnOkButtonClick()
References McBlockEntryChooser.BlockEntrance, DIMEN, MapBlock.Entrance, McExitDirectionChooser.exit, MapBlock.Exit, McExitDirectionChooser.hasExit, MapBlock.HasExit, HideDialog, mapBlocks, PATH_TO_GRIDS, RefreshFileList.
void McFileManager.OnCancelButtonClick()
References HideDialog.
static MapBlock McFileManager.Deserialize(string path)
static MapBlock McFileManager.Deserialize(TextReader reader)