McGrid
const int McGrid.HORISONTAL_BLOCK_COUNT
Referenced by DrawBlockAreas, DrawGrid, DrawInputedBlock, McGridConstructController.OnPointerDown.
const int McGrid.VERTICAL_BLOCK_COUNT
Referenced by DrawBlockAreas, DrawGrid, DrawInputedBlock, McGridConstructController.OnPointerDown.
Color McGrid.DEFAULT_CELLS_FILL_GRID_COLOR
Color McGrid.DEFAULT_CELLS_EMPTY_GRID_COLOR
Referenced by DrawGrid.
Color McGrid.SELECTEDT_GRID_COLOR
Referenced by DrawGrid.
Color McGrid.BLOCK_GRID_COLOR
Referenced by DrawGrid, OnDrawGizmos.
Color McGrid.DEFAULT_CELLS_FILL_INPUTED_GRID_COLOR
Referenced by DrawInputedBlock.
Color McGrid.DEFAULT_CELLS_EMPTY_INPUTED_GRID_COLOR
Referenced by DrawInputedBlock.
int McGrid.gridWidth
Referenced by DrawGrid, DrawInputedBlock, FillCell, Start.
int McGrid.gridHeight
Referenced by DrawGrid, DrawInputedBlock, FillCell, Start.
Vector2 McGrid.selectedBlocksPosition
Referenced by DrawGrid, GetSelectedBlocks.
MapBlock McGrid.inputedMapBlock
Referenced by DrawInputedBlock, InputMapBlock.
Vector2 McGrid.inputedMapBlockPosition
Referenced by DrawInputedBlock, InputMapBlock.
McGridConstructController McGrid.controller
Referenced by DrawGrid, Start.
bool McGrid.hasInputedBlock
Referenced by DrawInputedBlock, McGridConstructController.OnDrag, McGridConstructController.OnPointerDown, ReseteInputMapBlock.
bool [][] McGrid.Grid
if true - wall in this plase, cant walc if false - empty cell, can walc
Referenced by DrawGrid, FillCell, GetSelectedBlocks, InputMapBlock, OnDrawGizmos, Start.
MapBlock McGrid.InputedMapBlock
void McGrid.Start()
References controller, Grid, gridHeight, gridWidth.
void McGrid.DrawBlockAreas()
References MapBlock.BLOCK_SCALE, HORISONTAL_BLOCK_COUNT, VERTICAL_BLOCK_COUNT, MapBlock.WORLD_BLOCK_SIZE.
Referenced by OnDrawGizmos.
void McGrid.DrawGrid(Vector2 mousePosition)
References BLOCK_GRID_COLOR, MapBlock.BLOCK_SCALE, MapBlock.BLOCK_SIZE, McToggleTypeOfBlock.BlocksSelected, controller, DEFAULT_CELLS_EMPTY_GRID_COLOR, McFileManager.DialogShowed, Grid, gridHeight, gridWidth, McToggleTypeOfBlock.Height, HORISONTAL_BLOCK_COUNT, selectedBlocksPosition, SELECTEDT_GRID_COLOR, VERTICAL_BLOCK_COUNT, MapBlock.WORLD_BLOCK_SIZE.
Referenced by OnDrawGizmos.
void McGrid.DrawInputedBlock(Vector2 mousePosition)
References MapBlock.BLOCK_SCALE, MapBlock.BLOCK_SIZE, DEFAULT_CELLS_EMPTY_INPUTED_GRID_COLOR, DEFAULT_CELLS_FILL_INPUTED_GRID_COLOR, MapBlock.Grid, gridHeight, gridWidth, hasInputedBlock, HORISONTAL_BLOCK_COUNT, inputedMapBlock, inputedMapBlockPosition, VERTICAL_BLOCK_COUNT, MapBlock.WORLD_BLOCK_SIZE.
Referenced by OnDrawGizmos.
void McGrid.OnDrawGizmos()
References BLOCK_GRID_COLOR, DrawBlockAreas, DrawGrid, DrawInputedBlock, Grid.
void McGrid.InputMapBlock()
References MapBlock.BLOCK_SIZE, MapBlock.Grid, Grid, inputedMapBlock, inputedMapBlockPosition, ReseteInputMapBlock.
void McGrid.ReseteInputMapBlock()
References hasInputedBlock.
Referenced by InputMapBlock.
MapBlock McGrid.GetSelectedBlocks()
References MapBlock.BLOCK_SIZE, Grid, selectedBlocksPosition.
void McGrid.FillCell(Vector2 coordinates, float brushSize, bool fill)
References MapBlock.BLOCK_SCALE, Grid, gridHeight, gridWidth.