Unit
Action Unit.OnAnyUnitDeath
Referenced by Death.
Action<GameObject> Unit.OnArmsChanged
Action<GameObject> Unit.OnLegsChanged
Action<GameObject> Unit.OnHelmetChanged
Action<GameObject> Unit.OnBodyChanged
Action<GameObject> Unit.OnShieldChanged
Action<GameObject> Unit.OnWeaponChanged
Action<bool> Unit.OnRunValueChanged
Action<bool> Unit.OnChargingValueChanged
Action Unit.AfterInitiate
Referenced by Init.
Action Unit.OnUnitDeath
Referenced by Death.
Action<bool> Unit.OnHitChanged
Флаг, который будет включатся при нанесении врагу удара, и сразу выключатся (в следующем кадре).
UnitPosition Unit.TargetMovePositionObject
Referenced by Awake, MovingInPhalanx, MovingInRanks, OnReformInPhalanx, Squad.UnitDeath.
Squad Unit.squad
Referenced by AfterTakingDamage, CheckEquipment, CheckToUnion, Death, FindTarget, FixedUpdate, GetColorByHealth, Init, Moving, MovingInPhalanx, OnChargeHit, OnFormationChanged, OnPushEnd, OnPushStart, SetEquipment, Squad_OnInitiateUnitPositions, TakeHitFromArrow, TakeHitFromUnit, Update.
float Unit.delayToFindTargetAndAttack
Все юниты ищут цель в один кадр, и атакуют тоже в один кадр. Это садит фпс. Добавим задержку для таймера поиска цели. Это размажет выполнение функции по большему отрезку времени.
Referenced by Update.
UnitPosition Unit.unitPosOriginal
Referenced by Awake.
GameObject Unit.DroppedItemOriginal
Referenced by OnDropStack.
Transform Unit.DroppedItemsContainer
Referenced by OnDropStack.
Transform Unit.shadow
GameObject Unit.arms
GameObject Unit.legs
GameObject Unit.arms_with_spear
Referenced by SetWeapon.
GameObject Unit.arms_with_sword
Referenced by SetWeapon.
GameObject Unit.arms_with_pike
Referenced by SetWeapon.
UnitStats Unit.stats
Referenced by FindTarget, FixedUpdate, OnChargeHit, SetDistanceLineForAttack, SetProperties, TakeHitFromArrow, TakeHitFromUnit.
float Unit.currentSpeed
Referenced by FixedUpdate, MovingInPhalanx, OnChargeHit.
float Unit.movingRange
Referenced by CheckPositionInRange.
float Unit.rotationRange
Referenced by CheckRotationInRange.
float Unit.attackLineLength
Referenced by Cast, SetDistanceLineForAttack.
float Unit.attackLineWidth
Referenced by Cast.
float Unit.delayAfterTakingDamage
Referenced by TakeStan.
float Unit.delayAfterPushingAlly
Referenced by Update.
float Unit.findTargetDeltaTime
Referenced by Update.
float Unit.attacInRanksDeltaTime
Referenced by OnFormationChanged.
float Unit.attacInPhalanxDeltaTime
Referenced by OnFormationChanged.
float Unit.frontPushingAngleException
Referenced by OnPushStart.
float Unit.pushingAngle
Referenced by OnPushStart.
float Unit.chargePpushingAngle
Referenced by OnChargeHit.
float Unit.weaponAngleDeviation
Referenced by OnReformInPhalanx.
new Rigidbody2D Unit.rigidbody2D
Referenced by Awake, Death.
CircleCollider2D Unit.circleCollider2D
Referenced by Awake.
GameObject Unit.selection
Referenced by Awake.
SpriteRenderer Unit.selectionRenderer
Referenced by Awake.
bool Unit.selected
Referenced by CheckToUnion, FindTarget.
bool Unit.stanned
Referenced by FixedUpdate, Moving, OnDrawGizmos, Stan, Update.
Transform Unit.startRay
Referenced by Awake, Cast, SetDistanceLineForAttack.
Transform Unit.endRay
Referenced by Awake, Cast, RotateBody, SetDistanceLineForAttack.
float Unit.currentAttackDeltaTime
Referenced by OnFormationChanged, Update.
float Unit.unionCheckDeltatime
Referenced by Update.
int Unit.rHitLayerEnemy
Referenced by FindTarget, SetFraction.
RaycastHit2D Unit.rHit
Referenced by FindTarget.
Unit Unit.target
Referenced by AttackTarget, Death, FindTarget, MovingInPhalanx, MovingInRanks, MovingToTarget, OnPushStart, SetTarget, TakeHitFromUnit.
float Unit.takeHit
шанс получить удар от врага
Referenced by TakeHitFromUnit.
Vector2 Unit.v1
Vector2 Unit.v2
GameObject Unit._helmet
Equipment Unit.helmet
Referenced by CheckEquipment, Death.
GameObject Unit._body
Equipment Unit.body
Referenced by CheckEquipment, Death, RotateBody.
GameObject Unit._shield
Equipment Unit.shield
Referenced by CheckEquipment, Death.
GameObject Unit._weapon
Equipment Unit.weapon
Referenced by CheckEquipment, Death, RotateBody.
bool Unit.pushingAlly
Referenced by FixedUpdate, Moving, OnDrawGizmos, OnFormationChanged, OnPushStart, Update.
List<Unit> Unit.pushedUnit
Referenced by OnPushEnd, Update.
List<Unit> Unit.targettedBy
список всех юнитов который атакуют данный юнит (который взяли данный юнит как target)
Referenced by AddTargettedBy, Death, OnDrawGizmos, RemoveTagrettedBy.
bool Unit.attaking
Referenced by Death, OnDrawGizmos, SetAttakingFlag.
bool Unit.olreadyNotPushingAlly
Referenced by OnPushEnd, Update.
float Unit.timerForAttack
Referenced by AttackTarget, Update.
float Unit.timerForFindTarget
Referenced by FindTarget, Update.
float Unit.timerPushingAlly
Referenced by Update.
float Unit.timerForUnion
Referenced by CheckToUnion, Update.
bool Unit.running
bool Unit.charging
Quaternion Unit.chargeRotation
Referenced by MovingInRanks, Squad_OnBeginCharge.
int Unit.normLayer
Referenced by Init, Stan, Start.
bool Unit.hit
float Unit.timerForCheckEquipment
Referenced by CheckEquipment, Update.
GameObject Unit.Shadow
Referenced by UnitAnimationController.Death.
GameObject Unit.Arms
Referenced by UnitAnimationController.Awake, SetArms.
GameObject Unit.Legs
Referenced by UnitAnimationController.Awake.
float Unit.Health
Referenced by GetColorByHealth, Squad_OnUnitStatsChanged, TakeDamage.
UnitStats Unit.Stats
Referenced by HospitalRoom.ResetConverter, TakeHitFromArrow.
float Unit.CurrentSpeed
Referenced by MovingInPhalanx, MovingInRanks, MovingToTarget.
float Unit.MovingRange
float Unit.RotationRange
bool Unit.Selected
Referenced by FindTarget, Init, SetFraction, TakeHitFromUnit.
bool Unit.Stanned
Transform Unit.ThisTransform
Referenced by Awake, MovingInRanks, MovingToTarget, OnChargeHit, OnDropStack, OnPushStart, SetArms, SetBody, SetHelmet, SetShield, SetWeapon, ShowPopUpTakenDamageText, TakeHitFromUnit.
GameObject Unit.Helmet
Referenced by SetHelmet.
GameObject Unit.Body
Referenced by SetBody.
GameObject Unit.Shield
Referenced by SetShield.
GameObject Unit.Weapon
Referenced by SetWeapon.
bool Unit.Running
Referenced by FixedUpdate, MovingInPhalanx, MovingInRanks, MovingToTarget, TakeStan.
bool Unit.Charging
Referenced by MovingInRanks, OnChargeHit, OnCollisionEnter2D, Squad_OnBeginCharge, Squad_OnEndCharge, TakeStan.
bool Unit.Hit
Referenced by AttackTarget, Update.
void Unit.Awake()
References circleCollider2D, endRay, rigidbody2D, selection, selectionRenderer, startRay, TargetMovePositionObject, ThisTransform, unitPosOriginal.
void Unit.Start()
References normLayer, SetDistanceLineForAttack, Squad_OnInitiateUnitPositions.
void Unit.Squad_OnUnitStatsChanged(UnitStats oldS, UnitStats newS)
References UnitStats.Health, Health, SetProperties.
Referenced by Death, Init.
void Unit.Squad_OnBeginCharge(float addSpeed, float addAcceleretion)
References chargeRotation, Charging.
Referenced by Death, Init.
void Unit.Squad_OnEndCharge(float addSpeed, float addAcceleretion)
References Charging.
Referenced by Death, Init.
void Unit.Squad_OnInitiateUnitPositions()
References squad.
Referenced by Death, Init, Start.
void Unit.Squad_OnDrawUnitHpChanged(bool newValue)
References OnHealthChanged.
Referenced by Death, Init.
void Unit.OnHealthChanged(bool drawHp)
References GetColorByHealth.
Referenced by Squad_OnDrawUnitHpChanged.
void Unit.SetEquipment()
References Inventory.Body, Inventory.Helmet, Squad.Inventory, SetBody, SetHelmet, SetShield, SetWeapon, Inventory.Shield, squad, Inventory.Weapon.
Referenced by Init.
void Unit.SetWeapon(Equipment weapon)
References arms_with_pike, arms_with_spear, arms_with_sword, EquipmentStats.CanReformToPhalanx, EquipmentStats.CanReformToPhalanxInFight, Item.MainPropertie, Item.MainProperties.PathToPrefab, SetArms, Equipment.Stats, ThisTransform, Weapon.
Referenced by CheckEquipment, SetEquipment.
void Unit.SetShield(Equipment shield)
References Item.MainPropertie, Item.MainProperties.PathToPrefab, Shield, ThisTransform.
Referenced by CheckEquipment, SetEquipment.
void Unit.SetArms(GameObject arms)
References Arms, ThisTransform.
Referenced by SetWeapon.
void Unit.SetProperties()
References stats.
Referenced by CheckEquipment, OnFormationChanged, Squad_OnUnitStatsChanged.
RaycastHit2D Unit.Cast(int layers)
References attackLineLength, attackLineWidth, endRay, SetDistanceLineForAttack, startRay.
Referenced by FindTarget.
void Unit.SetDistanceLineForAttack()
References UnitStats.AttackDistance, attackLineLength, endRay, startRay, stats.
Referenced by Cast, Start.
void Unit.Update()
References AttackTarget, CheckEquipment, CheckToUnion, currentAttackDeltaTime, delayAfterPushingAlly, delayToFindTargetAndAttack, FindTarget, findTargetDeltaTime, Hit, olreadyNotPushingAlly, pushedUnit, pushingAlly, squad, stanned, timerForAttack, timerForCheckEquipment, timerForFindTarget, timerForUnion, timerPushingAlly, unionCheckDeltatime.
void Unit.CheckToUnion()
References Squad.DistanceToUnionWithSquad, Squad.FULL_SQUAD_UNIT_COUNT, Squad.InFight, Squad.playerSquadInstance, selected, squad, timerForUnion, Squad.UnitCount.
Referenced by Update.
void Unit.FindTarget()
References UnitStats.AttackDistance, Cast, Squad.CurrentFormation, rHit, rHitLayerEnemy, selected, Selected, SetTarget, squad, stats, target, timerForFindTarget.
Referenced by Update.
void Unit.AttackTarget()
References Hit, SetAttakingFlag, target, timerForAttack.
Referenced by Update.
void Unit.SetAttakingFlag(bool flag)
References attaking.
Referenced by AttackTarget.
void Unit.OnReformSquad(FormationStats.Formations newFormation)
References OnReformInPhalanx, OnReformInRanks.
Referenced by Death, Init.
void Unit.OnReformInRanks()
References RotateBody.
Referenced by OnReformSquad.
void Unit.OnReformInPhalanx()
References RotateBody, UnitPosition.RowInPhalanx, TargetMovePositionObject, weaponAngleDeviation.
Referenced by OnReformSquad.
void Unit.RotateBody(float angle)
References body, endRay, weapon.
Referenced by OnReformInPhalanx, OnReformInRanks.
void Unit.OnDropStack(EquipmentStack stack)
References EquipmentStack.Count, DroppedItemOriginal, DroppedItemsContainer, EquipmentStack.EquipmentMainProperties, EquipmentStack.EquipmentStats, ThisTransform.
Referenced by Death, Init.
void Unit.CheckEquipment()
References Inventory.Body, body, Inventory.Helmet, helmet, EquipmentStats.Id, Squad.Inventory, SetBody, SetHelmet, SetProperties, SetShield, SetWeapon, Inventory.Shield, shield, squad, Equipment.Stats, timerForCheckEquipment, Inventory.Weapon, weapon.
Referenced by Update.
void Unit.OnFormationChanged(FormationStats.Formations newFormation)
References attacInPhalanxDeltaTime, attacInRanksDeltaTime, currentAttackDeltaTime, Squad.CurrentFormation, pushingAlly, SetProperties, squad.
Referenced by Death, Init.
void Unit.FixedUpdate()
References currentSpeed, Moving, pushingAlly, Running, UnitStats.Speed, squad, stanned, stats.
void Unit.TakeHitFromUnit(Unit enemy)
References Damage.ArmourDamage, Squad.CurrentFormation, UnitStats.Damage, UnitStats.DefenceHalfSector, Selected, SetTarget, squad, stats, TakeDamage, takeHit, target, ThisTransform.
void Unit.TakeDamage(float damage, Squad owner, Unit enemy=null)
References AfterTakingDamage, Health.
Referenced by OnChargeHit, TakeHit, TakeHitFromArrow, TakeHitFromUnit.
void Unit.AddTargettedBy(Unit unit)
References targettedBy.
void Unit.RemoveTagrettedBy(Unit unit)
References targettedBy.
void Unit.SetTarget(Unit newTarget)
References target.
Referenced by FindTarget, TakeHitFromUnit.
void Unit.AfterTakingDamage(float dmg, Squad owner)
События после получения урона
enemy Вгар, который нанес урон /// dmg Урон, который нанес враг
References Squad.CurrentFormation, Squad.playerSquadInstance, ShowPopUpTakenDamageText, squad, TakeStan.
Referenced by TakeDamage.
void Unit.ShowPopUpTakenDamageText(string text, bool friendly=false)
References PopUpTextController.AddTextLabel, GraphixSettings.DamageToEnemyColor, Settings.graphixSettings, GameManager.Instance, PopUpTextController.Instance, GameManager.Settings, GraphixSettings.ShowDamage, ThisTransform.
Referenced by AfterTakingDamage, TakeHitFromArrow.
IEnumerator Unit.Stan(float delay)
После получения урона, юнит будет застанен. Перед тем как позволить ему снова двигаться пройдет указанная задержка.
References normLayer, stanned.
Referenced by TakeStan.
void Unit.MovingToTarget()
References calcTargetRotations, CurrentSpeed, GoTo, LookTo, Running, target, ThisTransform.
Referenced by MovingInRanks.
void Unit.Moving()
References Squad.CurrentFormation, MovingInPhalanx, MovingInRanks, MovingInRiseshields, pushingAlly, squad, stanned.
Referenced by FixedUpdate.
void Unit.MovingInRiseshields()
References MovingInRanks.
Referenced by Moving.
void Unit.MovingInPhalanx()
References CheckPositionInRange, currentSpeed, CurrentSpeed, Squad.endLookRotation, GoTo, LookTo, Running, squad, target, TargetMovePositionObject.
Referenced by Moving.
void Unit.MovingInRanks()
References calcTargetRotations, chargeRotation, Charging, CheckPositionInRange, CurrentSpeed, GoTo, LookTo, MovingToTarget, Running, target, TargetMovePositionObject, ThisTransform.
Referenced by Moving, MovingInRiseshields.
Quaternion Unit.calcTargetRotations(Vector3 targetPosition)
Referenced by MovingInRanks, MovingToTarget.
bool Unit.CheckRotationInRange(Quaternion targetRotation)
References rotationRange.
bool Unit.CheckPositionInRange(Vector3 targetPosition)
References movingRange.
Referenced by MovingInPhalanx, MovingInRanks.
void Unit.GoTo(Vector2 force)
Referenced by MovingInPhalanx, MovingInRanks, MovingToTarget.
void Unit.LookTo(Quaternion lookRotation)
Referenced by MovingInPhalanx, MovingInRanks, MovingToTarget.
void Unit.OnPushStart(Collision2D collision)
References Squad.CurrentFormation, frontPushingAngleException, Squad.InFight, pushingAlly, pushingAngle, squad, target, ThisTransform.
Referenced by OnCollisionEnter2D.
void Unit.OnPushEnd(Collision2D collision)
References Squad.CurrentFormation, olreadyNotPushingAlly, pushedUnit, squad.
Referenced by OnCollisionExit2D.
void Unit.OnChargeHit(Collision2D collision)
References Damage.ArmourDamage, chargePpushingAngle, Charging, currentSpeed, UnitStats.Damage, squad, stats, TakeDamage, TakeStan, ThisTransform.
Referenced by OnCollisionEnter2D.
void Unit.OnCollisionEnter2D(Collision2D collision)
References Charging, OnChargeHit, OnPushStart.
void Unit.OnCollisionExit2D(Collision2D collision)
References OnPushEnd.
void Unit.OnDrawGizmos()
References attaking, pushingAlly, stanned, targettedBy.
void Unit.Init()
References AfterInitiate, Squad.CurrentFormation, normLayer, OnDropStack, OnFormationChanged, OnReformSquad, Selected, SetEquipment, squad, Squad_OnBeginCharge, Squad_OnDrawUnitHpChanged, Squad_OnEndCharge, Squad_OnInitiateUnitPositions, Squad_OnUnitStatsChanged.
void Unit.Death()
References attaking, body, EquipmentStats.Empty, helmet, Squad.Inventory, OnAnyUnitDeath, OnDropStack, OnFormationChanged, OnReformSquad, OnUnitDeath, rigidbody2D, shield, squad, Squad_OnBeginCharge, Squad_OnDrawUnitHpChanged, Squad_OnEndCharge, Squad_OnInitiateUnitPositions, Squad_OnUnitStatsChanged, Equipment.Stats, target, targettedBy, Squad.UnitCount, weapon.
void Unit.SetFraction(Squad.UnitFraction fraction)
References rHitLayerEnemy, Selected.
Color Unit.GetColorByHealth()
References Health, squad.
Referenced by OnHealthChanged.
void Unit.SetBody(Equipment body)
References Body, Item.MainPropertie, Item.MainProperties.PathToPrefab, ThisTransform.
Referenced by CheckEquipment, SetEquipment.
void Unit.SetHelmet(Equipment helmet)
References Helmet, Item.MainPropertie, Item.MainProperties.PathToPrefab, ThisTransform.
Referenced by CheckEquipment, SetEquipment.
void Unit.TakeHitFromArrow(Damage damage, ArrowsValley valley)
References UnitStats.Armour, Damage.ArmourDamage, Squad.CurrentFormation, UnitStats.DefenceHalfSector, EquipmentStats.Empty, Squad.Inventory, UnitStats.MissileBlock, ArrowsValley.owner, Squad.playerSquadInstance, Inventory.Shield, ShowPopUpTakenDamageText, squad, Equipment.Stats, stats, Stats, TakeDamage.
void Unit.TakeHit(Damage damage)
Нанести удар по юниту.
Урон будет расчитан с учетом брони юнита, но без учета вероятности попадания по нему (его параметра защиты). damage
References Damage.ArmourDamage, TakeDamage.
void Unit.Heal(float health)
void Unit.TakeStan(float a=1)
References Charging, delayAfterTakingDamage, Running, Stan.
Referenced by AfterTakingDamage, OnChargeHit.
void Unit.SetSelectionColor(Color color)