DialogBox
GameObject DialogBox.originalButton
Referenced by Show.
TextMeshProUGUI DialogBox.title
Referenced by SetTitle.
GameObject DialogBox.iconContent
Image DialogBox.icon
GameObject DialogBox.scrolableTextContent
TextMeshProUGUI DialogBox.scrolableText
GameObject DialogBox.unscrolableTextContent
TextMeshProUGUI DialogBox.unscrolableText
Transform DialogBox.buttonsPanel
Referenced by Reset, Show.
string DialogBox.defaultTitle
Referenced by Reset.
string DialogBox.defaultText
Referenced by Reset.
Color DialogBox.defaultTitleColor
Referenced by Show.
Color DialogBox.defaultTextColor
Referenced by Show.
DialogData DialogBox.dialogData
Referenced by Awake, Show.
Vector2 DialogBox.startPosition
Referenced by Awake, Hide.
RectTransform DialogBox.thisTansform
Referenced by Awake.
CanvasGroup DialogBox.cg
Referenced by Awake.
ContentSizeFitter DialogBox.fitter
Referenced by Awake.
DialogBox DialogBox.Instance
Referenced by Awake, PauseToggle.onValChanged.
bool DialogBox.Showned
Referenced by Hide, PauseToggle.onValChanged, Show.
object DialogBox.Owner
Referenced by PauseToggle.onValChanged, Show.
void DialogBox.Awake()
References cg, dialogData, fitter, Hide, Instance, startPosition, thisTansform.
void DialogBox.Reset()
References buttonsPanel, defaultText, defaultTitle.
Referenced by Show.
void DialogBox.Show(object owner=null)
void DialogBox.Show(Vector2 positionOnScreen, object owner=null)
References DialogBox.DialogData.ButtonsData, buttonsPanel, defaultTextColor, defaultTitleColor, dialogData, DialogBox.DialogData.Height, DialogBox.DialogData.Icon, DialogBox.DialogData.IsTextScrolable, originalButton, Owner, DialogBox.DialogData.PrefButtonHeight, Reset, Showned, DialogBox.DialogData.Text, DialogBox.DialogData.TextColor, DialogBox.DialogData.Title, DialogBox.DialogData.TitleColor, DialogBox.DialogData.Wifth.
void DialogBox.Hide()
References Showned, startPosition.
Referenced by AddCancelButton, Awake.
IDialogBox DialogBox.SetTitle(string title)
References title.
IDialogBox DialogBox.SetText(string text, bool isScrolable=false)
IDialogBox DialogBox.AddButton(string text, Action action)
IDialogBox DialogBox.AddCancelButton(string text)
References Hide.
IDialogBox DialogBox.SetIcon(Sprite sprite)
IDialogBox DialogBox.SetTitleColor(Color color)
IDialogBox DialogBox.SetTextColor(Color color)
IDialogBox DialogBox.SetPrefButtonHeight(float prefHeight)
IDialogBox DialogBox.SetSize(float?width=null, float?height=null)