GameManager
GameManager GameManager.Instance
Referenced by Awake, DropToEquipmentMarket.CanGetFromThisIventory, ToMainmenu.FadeOn, Ground.GetExitDirection, Ground.LoadMapBlocks, CoureWorkConnectToServer.OnClickOk, CallConverterNumberPicker.OnPointerClick, PlayerSquadPathFinderController.OnPointerDown, PlayerSquadController.OnPointerDown, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp, HospitalRoom.ResetConverter, Unit.ShowPopUpTakenDamageText, Exit.Start, Ground.Start.
bool GameManager.GamePaused
Referenced by ToMainmenu.FadeOn, PlayerSquadPathFinderController.OnPointerDown, PlayerSquadController.OnPointerDown, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp, Pause, Resume, Update.
PlayerProgress GameManager.PlayerProgress
Referenced by DropToEquipmentMarket.CanGetFromThisIventory, CallConverterNumberPicker.OnPointerClick, ResetAllProgress, HospitalRoom.ResetConverter.
Settings GameManager.Settings
Referenced by ResetAllSettings, Unit.ShowPopUpTakenDamageText.
bool GameManager.ControlGroundSize
Referenced by Ground.Start.
int GameManager.RowCount
int GameManager.ColCount
int GameManager.Level
Squad GameManager.PlayerSquad
ISavingManager GameManager.SavingManager
Referenced by CoureWorkConnectToServer.OnClickOk.
bool GameManager.gamePaused
PlayerProgress GameManager.playerProgress
Referenced by ResetAllProgress.
float GameManager.timeScale
Referenced by Resume, Update.
Settings GameManager.settings
Referenced by ResetAllSettings.
bool GameManager.controlGroundSize
int GameManager.rows
Referenced by ReconfigureLevelSettings.
int GameManager.cols
Referenced by ReconfigureLevelSettings.
float GameManager.defFixedDeltaTime
Referenced by Awake, Update.
int GameManager.level
Referenced by Awake, LoadMainMenu, LoadMarket, LoadNextLevel, OnGUI, ReconfigureLevelSettings.
Squad GameManager.squad
Referenced by InitPlayer, OnGUI.
float GameManager.timer
Referenced by OnGUI.
string GameManager.fps
Referenced by OnGUI.
string GameManager.s1
Referenced by OnGUI.
string GameManager.s2
Referenced by OnGUI.
McGridConstructController.GroundType GameManager.GroundType
Referenced by Ground.LoadMapBlocks.
Vector2 GameManager.entranceBlockPosition
начальная позиция игрока на крте
Referenced by InitPlayer, Exit.Start.
Vector2 GameManager.exitBlockPosition
позиция на карте для перехода на следующий уровень
MapBlock.Direction GameManager.exitDirection
Referenced by Ground.GetExitDirection.
MapBlock.Direction GameManager.entranceDirection
Action<int, int> GameManager.BeforeLoadLevel
первый агрумент - номер сцены, на которую будет совершен переход. второй агрумент - номер игрового уровня
Referenced by Awake, LoadMainMenu, LoadMarket, LoadNextLevel.
void GameManager.Awake()
References BeforeLoadLevel, defFixedDeltaTime, DownloadSaves, Instance, level, OnUnhendeledException, Pause, ResetPlayerNonmoneyScore.
void GameManager.OnUnhendeledException(string condition, string stackTrace, LogType type)
Referenced by Awake.
void GameManager.OnApplicationQuit()
References ResetPlayerNonmoneyScore.
void GameManager.Update()
References defFixedDeltaTime, GamePaused, timeScale.
void GameManager.ReconfigureLevelSettings()
References cols, level, rows.
Referenced by LoadMainMenu, LoadNextLevel.
void GameManager.OnApplicationPause(bool pause)
void GameManager.OnGUI()
References fps, level, s1, s2, squad, timer.
void GameManager.DownloadSaves()
Referenced by Awake.
void GameManager.ResetPlayerNonmoneyScore()
Золото сбрасывать НЕЛЬЗЯ !!! Это покупная валюта!
Referenced by Awake, OnApplicationQuit.
void GameManager.WaitForLevelGenerated()
void GameManager.InitPlayer()
References MapBlock.BLOCK_SCALE, entranceBlockPosition, MapBlock.Exit, Squad.playerSquadInstance, Squad.PositionsTransform, squad, MapBlock.WORLD_BLOCK_SIZE.
void GameManager.SetPause(bool pause)
References Pause, Resume.
void GameManager.Pause()
References GamePaused.
Referenced by Awake, SetPause.
void GameManager.Resume()
References GamePaused, timeScale.
Referenced by SetPause.
void GameManager.LoadNextLevel()
References BeforeLoadLevel, level, ReconfigureLevelSettings.
void GameManager.LoadMarket()
References BeforeLoadLevel, level.
void GameManager.LoadMainMenu()
References BeforeLoadLevel, level, Squad.playerSquadInstance, ReconfigureLevelSettings.
void GameManager.ResetAllSettings()
References settings, Settings.
void GameManager.ResetAudioSettings()
void GameManager.ResetCommonSettings()
void GameManager.ResetGraphixSettings()
void GameManager.ResetAllProgress()
References playerProgress, PlayerProgress.
void GameManager.ResetScore()
void GameManager.ResetStats()
void GameManager.ResetSkills()