PlayerSquadPathFinderController
Camera PlayerSquadPathFinderController.cameraToControl
Referenced by Start.
Squad PlayerSquadPathFinderController.squadToControl
Referenced by OnPointerDown, OnPointerUp, Start.
float PlayerSquadPathFinderController.lookVectorDistanse
Referenced by OnPointerUp.
List<Vector3> PlayerSquadPathFinderController.path
Referenced by FindPath, OnPointerUp.
Vector2 PlayerSquadPathFinderController.startFindPath
Referenced by FindPath, OnPointerUp.
Vector2 PlayerSquadPathFinderController.endFindPath
Referenced by FindPath, OnPointerUp.
Vector3 PlayerSquadPathFinderController.lookPosition
Referenced by OnPointerDown, OnPointerUp.
Vector3 PlayerSquadPathFinderController.movePosition
Referenced by FindPath, OnPointerDown, OnPointerUp.
Quaternion PlayerSquadPathFinderController.lookRotation
Referenced by FindPath, OnPointerUp.
bool PlayerSquadPathFinderController.mouseDown
Referenced by OnPointerDown, OnPointerUp.
int PlayerSquadPathFinderController.touchId
Referenced by OnPointerDown, OnPointerUp.
Ground PlayerSquadPathFinderController.ground
Referenced by OnPointerUp, Start.
Thread PlayerSquadPathFinderController.thread
Referenced by OnPointerUp.
RawImage PlayerSquadPathFinderController.minimap
Referenced by Start.
void PlayerSquadPathFinderController.Start()
References cameraToControl, ground, Ground.Instance, minimap, Squad.playerSquadInstance, squadToControl.
Vector2 PlayerSquadPathFinderController.TextureToWorldPosition(Vector2 touchPos)
References Ground.ColCountOfBlocks, Ground.Instance, Ground.RowCountOfBlocks, MapBlock.WORLD_BLOCK_SIZE.
Referenced by OnPointerDown, OnPointerUp.
void PlayerSquadPathFinderController.FindPath()
References MapBlock.BLOCK_SCALE, endFindPath, lookRotation, movePosition, path, startFindPath.
Referenced by OnPointerUp.
void PlayerSquadPathFinderController.OnPointerDown(PointerEventData eventData)
References Squad.Charging, GameManager.GamePaused, GameManager.Instance, lookPosition, mouseDown, movePosition, squadToControl, TextureToWorldPosition, touchId.
void PlayerSquadPathFinderController.OnPointerUp(PointerEventData eventData)
References MapBlock.BLOCK_SCALE, Squad.Charging, Ground.ColCountOfBlocks, Squad.CurrentFormation, endFindPath, FindPath, GameManager.GamePaused, Ground.Grid, ground, GameManager.Instance, lookPosition, lookRotation, lookVectorDistanse, mouseDown, movePosition, path, Squad.PositionsTransform, Ground.RowCountOfBlocks, squadToControl, startFindPath, TextureToWorldPosition, thread, touchId, MapBlock.WORLD_BLOCK_SIZE.