ADropToMe
new Transform ADropToMe.transform
Referenced by DropToInventory.OnDrop, DropToSkill.OnDrop, Start.
void ADropToMe.Start()
References transform.
abstract void ADropToMe.OnDrop(PointerEventData eventData)
abstract bool ADropToMe.CanGetFromThisIventory(AStack aStack)
stack true если можно добавлять
Referenced by DropToGround.OnDrop, DropToConsumableMarket.OnDrop, DropToEquipmentMarket.OnDrop.
abstract bool ADropToMe.AddToThisInventory(AStack aStack)
stack true если добавление произошло удачно
abstract bool ADropToMe.RemoveFromThisInventory(AStack aStack)
stack true если удаление произошло удачно
Referenced by DropToGround.OnDrop, DropToConsumableMarket.OnDrop, DropToEquipmentMarket.OnDrop.
void ADropToMe.RefreshUI()
References SquadSkillsInventoryUI.Instance, SkillMarketInventoryUI.Instance, SquadInventoryUI.Instance, EnvirinmantInventoryUI.Instance, MarketInventoryUI.Instance.
Referenced by DropToGround.OnDrop, DropToEquipmentMarket.OnDrop, DropToEquipment.OnDrop, DropToInventory.OnDrop, DropToSkillMarket.OnDrop, DropToSkill.OnDrop.