Ground
const string Ground.PATH_TO_PREFABS
Referenced by InstantiateMapBlockSprite.
const string Ground.PATH_TO_GRIDS
Referenced by LoadMapBlocks.
int Ground.rowCountOfBlocks
Referenced by GeneradeMap, GetEntranceAndExit, GetExitDirection, Start.
int Ground.colCountOfBlocks
Referenced by GeneradeMap, GetEntranceAndExit, GetExitDirection, Start.
int Ground.seed
Referenced by GeneradeMap.
bool Ground.createRandom
Referenced by GeneradeMap, Start.
float Ground.rightWallsChanse
Referenced by GeneradeMap.
float Ground.topWallsChanse
Referenced by GeneradeMap.
bool Ground.willHaveLoops
Referenced by GeneradeMap.
float Ground.exitOnColPercentOfMap
Referenced by GetEntranceAndExit.
float Ground.exitOnRowPercentOfMap
Referenced by GetEntranceAndExit.
Camera Ground.minimapCamera
Referenced by Start.
bool [][] Ground.rightWalls
Referenced by GeneradeMap.
bool [][] Ground.topWalls
Referenced by GeneradeMap.
List<SameBlocksContainer> Ground.blockContainers
Referenced by FindMapBlock, LoadMapBlocks.
int Ground.indexType
Referenced by FindMapBlock.
int Ground.indexSame
Referenced by FindMapBlock.
System.Random Ground.rnd
Referenced by Start.
int Ground.fullCountOfBlock
Referenced by GeneradeMap.
int Ground.loadedBlockCount
Referenced by GeneradeMap.
float Ground.progress
Referenced by Awake, GeneradeMap.
bool Ground.generationIsDone
Referenced by Awake, GeneradeMap.
Ground Ground.Instance
Referenced by Awake, Exit.OnTriggerEnter2D, Exit.OnTriggerExit2D, ProgressCircle.Running, PlayerSquadPathFinderController.Start, PlayerSquadPathFinderController.TextureToWorldPosition.
int Ground.RowCountOfBlocks
Referenced by AiSquadController.GoTo, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp, PlayerSquadPathFinderController.TextureToWorldPosition.
int Ground.ColCountOfBlocks
Referenced by AiSquadController.GoTo, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp, PlayerSquadPathFinderController.TextureToWorldPosition.
GroundBlock [][] Ground.MiniGrid
Referenced by GeneradeMap.
bool [][] Ground.Grid
if true - wall in this plase, cant walc if false - empty cell, can walc
Referenced by GeneradeMap, AiSquadController.GoTo, InsertToGrid, OnDrawGizmos, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp.
float Ground.Progress
bool Ground.GenerationIsDone
Referenced by Exit.OnTriggerEnter2D, Exit.OnTriggerExit2D, ProgressCircle.Running.
Action Ground.OnGenerationDone
Referenced by GeneradeMap.
void Ground.Awake()
References generationIsDone, Instance, progress.
void Ground.Start()
References colCountOfBlocks, GameManager.ControlGroundSize, createRandom, GeneradeMap, GameManager.Instance, LoadMapBlocks, minimapCamera, rnd, rowCountOfBlocks, MapBlock.WORLD_BLOCK_SIZE.
void Ground.LoadMapBlocks()
References blockContainers, MapBlock.Exit, MapBlock.ExitString, GameManager.GroundType, MapBlock.HasExit, GameManager.Instance, PATH_TO_GRIDS.
Referenced by Start.
IEnumerator Ground.GeneradeMap()
References MapBlock.BLOCK_SIZE, colCountOfBlocks, createRandom, FindMapBlock, fullCountOfBlock, generationIsDone, GetEntranceAndExit, GetExitDirection, Grid, InsertToGrid, InstantiateMapBlockSprite, loadedBlockCount, MiniGrid, OnGenerationDone, progress, rightWalls, rightWallsChanse, rowCountOfBlocks, seed, topWalls, topWallsChanse, willHaveLoops, MapBlock.WORLD_BLOCK_SIZE.
Referenced by Start.
void Ground.GetEntranceAndExit(out Vector2 entranceBlockPosition, out Vector2 exitBlockPosition)
References colCountOfBlocks, exitOnColPercentOfMap, exitOnRowPercentOfMap, rowCountOfBlocks.
Referenced by GeneradeMap.
MapBlock.Direction Ground.GetExitDirection(MapBlock block, Vector2 positionInMinigrid, bool isExit)
References colCountOfBlocks, GameManager.exitDirection, GameManager.Instance, rowCountOfBlocks.
Referenced by GeneradeMap.
void Ground.InsertToGrid(MapBlock block)
References MapBlock.BLOCK_SCALE, MapBlock.BLOCK_SIZE, MapBlock.Grid, Grid, MapBlock.WorldPosition.
Referenced by GeneradeMap.
GroundBlock Ground.InstantiateMapBlockSprite(Vector2 position, string name)
References MapBlock.BLOCK_SCALE, PATH_TO_PREFABS, MapBlock.WORLD_BLOCK_SIZE.
Referenced by GeneradeMap.
void Ground.OnDrawGizmos()
References MapBlock.BLOCK_SCALE, Grid.
SameBlocksContainer.Block Ground.FindMapBlock(List< MapBlock.Direction > inclusionsDirection, List< MapBlock.Direction > exclusionsDirection, bool wantedExitBlock=false, MapBlock.Direction exitDirection=MapBlock.Direction.BOTTOM)
References blockContainers, indexSame, indexType.
Referenced by GeneradeMap.