HospitalRoom
HealTarget
NumberConverter HospitalRoom.converter
Referenced by Converter_OnCliclOk, ResetConverter.
Transform HospitalRoom.containerUnitHealthIdicators
Referenced by AddNewLines, RemoveOldLines.
Transform HospitalRoom.LineOriginalUnitHealthIndicator
Referenced by AddNewLines.
TMP_Dropdown HospitalRoom.healTarget
Referenced by Converter_OnCliclOk, Start.
CanvasGroup HospitalRoom.healControl
void HospitalRoom.Start()
References Converter_OnCliclOk, healTarget.
void HospitalRoom.OnEnable()
References AddNewLines, Squad.playerSquadInstance, ResetConverter.
void HospitalRoom.OnDisable()
References RemoveOldLines.
void HospitalRoom.Converter_OnCliclOk()
References converter, healTarget, HealUnits, NumberConverter.OutputValue, RereshLines, ResetConverter.
Referenced by Start.
bool HospitalRoom.ResetConverter()
References converter, UnitStats.Health, NumberConverter.InputValue, GameManager.Instance, NumberConverter.OutputValue, GameManager.PlayerProgress, PlayerProgress.score, DSPlayerScore.silver, Unit.Stats, DSPlayerScore.Score.Value.
Referenced by Converter_OnCliclOk, OnEnable.
float HospitalRoom.HealUnits(List< Unit > units, float health)
units health возвращает лишнее здоровье (которое никому больше не надо)
Referenced by Converter_OnCliclOk.
void HospitalRoom.AddNewLines()
References containerUnitHealthIdicators, LineOriginalUnitHealthIndicator, RereshLines.
Referenced by OnEnable.
void HospitalRoom.RemoveOldLines()
References containerUnitHealthIdicators.
Referenced by OnDisable.
void HospitalRoom.RereshLines()
Referenced by AddNewLines, Converter_OnCliclOk.