SkillButton
SkillNum
Skill.SkillUseType SkillButton.useType
Referenced by OnBeginDrag, OnDrag, OnEndDrag, OnPointerClick, Start.
SkillNum SkillButton.skillNum
Referenced by Start.
Text SkillButton.cooldownText
Image SkillButton.img
Referenced by Start.
CanvasGroup SkillButton.cg
Referenced by Start.
Inventory SkillButton.playerInventory
Referenced by Start.
Transform SkillButton.playerSquadTransform
Referenced by Start.
SkillStack SkillButton.currentSkill
Referenced by OnDrag, OnEndDrag, OnPointerClick, Start.
bool SkillButton.canCast
Referenced by OnBeginDrag, OnDrag, OnEndDrag, OnPointerClick, Start, WaitForCooldown.
LineRenderer SkillButton.lineRenderer
Referenced by Start.
float SkillButton.rHitCirclreAngle
Referenced by CreateSinCosAngles, Start.
int SkillButton.rHitCirclreSegmentCount
Referenced by CreatePoints, CreateSinCosAngles, OnDrag, Start.
Vector3 [] SkillButton.rHitCirclreSegments
Referenced by CreatePoints, OnDrag, Start.
float [] SkillButton.sinAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
float [] SkillButton.cosAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
void SkillButton.Start()
References canCast, cg, cosAngles, CreateSinCosAngles, currentSkill, img, lineRenderer, playerInventory, playerSquadTransform, rHitCirclreAngle, rHitCirclreSegmentCount, rHitCirclreSegments, sinAngles, SkillStack.Skill, skillNum, useType.
IEnumerator SkillButton.WaitForCooldown(float time)
References canCast.
Referenced by OnEndDrag, OnPointerClick.
void SkillButton.CreateSinCosAngles()
References cosAngles, rHitCirclreAngle, rHitCirclreSegmentCount, sinAngles.
Referenced by Start.
void SkillButton.CreatePoints(Vector2 center, float radius)
References cosAngles, rHitCirclreSegmentCount, rHitCirclreSegments, sinAngles.
Referenced by OnDrag.
void SkillButton.OnPointerClick(PointerEventData eventData)
References canCast, ISkillCooldownable.Cooldown, currentSkill, Skill.DoSkill, Squad.playerSquadInstance, SkillStack.Skill, SkillStack.SkillStats, useType, WaitForCooldown.
void SkillButton.OnDrag(PointerEventData eventData)
References canCast, CreatePoints, currentSkill, Squad.playerSquadInstance, rHitCirclreSegmentCount, rHitCirclreSegments, SkillStack.SkillStats, useType.
void SkillButton.OnEndDrag(PointerEventData eventData)
References canCast, ISkillCooldownable.Cooldown, currentSkill, Skill.DoSkill, Squad.playerSquadInstance, SkillStack.Skill, SkillStack.SkillStats, useType, WaitForCooldown.
void SkillButton.OnBeginDrag(PointerEventData eventData)
References canCast, Squad.playerSquadInstance, useType.