Durabilityable
float Durabilityable.brokenRotationRange
Случайный разброс поворота при уничтожении
Referenced by BreakDown.
float Durabilityable.brokenRrotation
Поворот при уничтожении
Referenced by BreakDown.
float Durabilityable.maximumDurability
Referenced by SetSprite, Start.
float Durabilityable.durability
Referenced by BreakDown, SetSprite, Start, TakeDamage.
float Durabilityable.resistance
Сопротивление этого объекта к урону
0 - урон проходит полностью, 1 - урон блокируется.
Referenced by TakeDamage.
Sprite [] Durabilityable.durabilitySprites
Referenced by SetSprite.
Sprite Durabilityable.brokenSprite
Referenced by SetSprite.
int Durabilityable.spritesCount
Referenced by SetSprite, Start.
SpriteRenderer Durabilityable.renderer
Referenced by Start.
Transform Durabilityable.thisTransform
Referenced by Start.
void Durabilityable.Start()
References durability, maximumDurability, renderer, SetSprite, spritesCount, thisTransform.
void Durabilityable.SetSprite(bool broken=false)
References brokenSprite, durability, durabilitySprites, maximumDurability, spritesCount.
Referenced by BreakDown, Start, TakeDamage.
bool Durabilityable.TakeDamage(float damage)
Нанести урон по этому разрушаемому объекту.
Урон будет нанесен с учетом сопротивления к урону этого объекта. damage Если объект был уничтожен, возвратится true.
References BreakDown, durability, resistance, SetSprite.
Referenced by Stakes.HitUnit.
void Durabilityable.BreakDown()
References brokenRotationRange, brokenRrotation, durability, SetSprite.
Referenced by TakeDamage.