Exit
int Exit.playersUnitCountITrigger
Referenced by OnDrawGizmos, OnTriggerEnter2D, OnTriggerExit2D.
float Exit.deltaTime
Referenced by CheckCenterSquadToExit.
Transform Exit.thisTransform
Referenced by Start.
Squad Exit.playerSquad
Referenced by CheckCenterSquadToExit, Start.
bool Exit.goToNextLevel
Referenced by CheckCenterSquadToExit, OnDrawGizmos, OnTriggerEnter2D, OnTriggerExit2D.
Collider2D Exit.collider
Referenced by CheckCenterSquadToExit, Start.
void Exit.Start()
References collider, GameManager.entranceBlockPosition, GameManager.Instance, playerSquad, GroundBlock.posInMinigrid, thisTransform.
IEnumerator Exit.CheckCenterSquadToExit()
References Squad.CenterSquad, collider, deltaTime, goToNextLevel, LoadLevel, playerSquad.
Referenced by OnTriggerEnter2D, OnTriggerExit2D.
IEnumerator Exit.LoadLevel()
Referenced by CheckCenterSquadToExit.
void Exit.OnTriggerEnter2D(Collider2D collision)
References CheckCenterSquadToExit, Ground.GenerationIsDone, goToNextLevel, Ground.Instance, playersUnitCountITrigger.
void Exit.OnTriggerExit2D(Collider2D collision)
References CheckCenterSquadToExit, Ground.GenerationIsDone, goToNextLevel, Ground.Instance, playersUnitCountITrigger.
void Exit.OnDrawGizmos()
References goToNextLevel, playersUnitCountITrigger.