SkillUpgradeButton
Image SkillUpgradeButton.icon
TextMeshProUGUI SkillUpgradeButton.costText
TextMeshProUGUI SkillUpgradeButton.currentLevelText
TextMeshProUGUI SkillUpgradeButton.maximumLevelText
GameObject SkillUpgradeButton.costPanel
string SkillUpgradeButton.nameResourceString
Referenced by GetDescription.
string SkillUpgradeButton.descriptionResourceString
Referenced by GetDescription.
string SkillUpgradeButton.upgradeStatDescriptionResourceString
Referenced by GetDescription.
Image SkillUpgradeButton.background
Color SkillUpgradeButton.lockedColor
Referenced by Refresh.
Color SkillUpgradeButton.unlockedColor
Referenced by Refresh.
Color SkillUpgradeButton.doneColor
Referenced by Refresh.
SkillsUpgrade SkillUpgradeButton.parent
SkillUpgradeButton [] SkillUpgradeButton.previousButton
Referenced by Awake, Refresh.
SkillUpgradeButton [] SkillUpgradeButton.nextButton
Referenced by Upgrade.
DSPlayerSkill.SkillUpgrade SkillUpgradeButton.upgradeStats
Referenced by GetDescription, Initiate, Refresh.
AnimationCurve SkillUpgradeButton.costDependency
int SkillUpgradeButton.minCost
Referenced by CalcLevelCost.
int SkillUpgradeButton.maxCost
Referenced by CalcLevelCost.
int SkillUpgradeButton.maxLevel
Referenced by CalcLevelCost, Refresh.
bool SkillUpgradeButton.isPositiveUpgrade
Referenced by GetDescription.
int SkillUpgradeButton.currentCost
Referenced by GetDescription, Refresh, Upgrade.
List<Action> SkillUpgradeButton.actions
Referenced by Initiate, OnPointerClick.
List<string> SkillUpgradeButton.actionsNames
Referenced by Initiate, OnPointerClick.
Button SkillUpgradeButton.btn
Referenced by Initiate, OnPointerClick.
UILineConnector SkillUpgradeButton.connector
Referenced by Awake, Refresh.
bool SkillUpgradeButton.locked
Referenced by Refresh.
DSPlayerSkill.SkillUpgrade SkillUpgradeButton.UpgradeStats
int SkillUpgradeButton.Id
void SkillUpgradeButton.Awake()
References connector, previousButton.
int SkillUpgradeButton.CalcLevelCost(int level)
References maxCost, maxLevel, minCost.
Referenced by Refresh.
void SkillUpgradeButton.Refresh()
References CalcLevelCost, connector, currentCost, doneColor, StringFormats.intSeparatorNumber, locked, lockedColor, maxLevel, StringFormats.nfi, previousButton, unlockedColor, upgradeStats.
Referenced by Initiate, Upgrade.
void SkillUpgradeButton.Upgrade()
References currentCost, nextButton, Refresh, Localization.toast_not_enough_expirience.
Referenced by Initiate.
void SkillUpgradeButton.Initiate(DSPlayerSkill.SkillUpgrade upgrade, bool load)
upgrade load передаем false и этот метод переприсвоит переданный в первом параметре апгрейд. если передадим true то будет загружен переданный в первом параметре апгрейд
References actions, actionsNames, btn, Localization.cancel, Refresh, Localization.upgrade, Upgrade, upgradeStats.
Description SkillUpgradeButton.GetDescription()
References currentCost, descriptionResourceString, StringFormats.floatSignNumber, isPositiveUpgrade, nameResourceString, upgradeStatDescriptionResourceString, upgradeStats.
Referenced by OnPointerClick.
void SkillUpgradeButton.OnPointerClick(PointerEventData eventData)
References actions, actionsNames, btn, GetDescription.