PlayerSquadController
PlayerSquadController PlayerSquadController.Instance
Referenced by Awake.
Squad PlayerSquadController.squad
Referenced by OnPointerDown, OnPointerUp, SetStartPosition, Start, Update.
Ground PlayerSquadController.ground
Referenced by OnPointerUp, Start.
LayerMask PlayerSquadController.directFindPathLayers
float PlayerSquadController.lookVectorDistanse
Referenced by OnPointerUp.
float PlayerSquadController.cicleCastRadius
Referenced by CircleCastConstrict, CreatePoints, SelectEnemyes.
float PlayerSquadController.circleConstrincInPercent
Referenced by CircleCastConstrict.
float PlayerSquadController.circleConstrincGuaranteeUnits
Referenced by CircleCastConstrict.
float PlayerSquadController.circleExpandDurationInSec
Referenced by CircleCastConstrict.
float PlayerSquadController.circleExpandDeltaTime
Referenced by CircleCastConstrict.
float PlayerSquadController.circleMinRadius
Referenced by CircleCastConstrict.
bool PlayerSquadController.coroutineAlive
Referenced by CircleCastConstrict.
float PlayerSquadController.rHitCirclreAngle
Referenced by CreateSinCosAngles, Start.
int PlayerSquadController.rHitCirclreSegmentCount
Referenced by CreatePoints, CreateSinCosAngles, Start, Update.
Vector3 [] PlayerSquadController.rHitCirclreSegments
Referenced by CreatePoints, Start, Update.
float [] PlayerSquadController.sinAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
float [] PlayerSquadController.cosAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
Thread PlayerSquadController.thread
Referenced by OnPointerUp.
List<Vector3> PlayerSquadController.path
Referenced by FindPath, OnPointerUp.
Vector2 PlayerSquadController.startFindPath
Referenced by FindPath, OnPointerUp.
Vector2 PlayerSquadController.endFindPath
Referenced by FindPath, OnPointerUp.
Vector3 PlayerSquadController.lookPosition
Referenced by OnPointerDown, OnPointerUp, Update.
Vector3 PlayerSquadController.movePosition
Referenced by FindPath, OnPointerDown, OnPointerUp, SelectEnemyes, SetStartPosition, Update.
Quaternion PlayerSquadController.lookRotation
Referenced by FindPath, OnPointerUp.
LineRenderer PlayerSquadController.lineRenderer
Referenced by Start.
int PlayerSquadController.maxHitsCount
Referenced by Start.
RaycastHit2D [] PlayerSquadController.rHits
Referenced by DeselectEnemyes, SelectEnemyes, Start.
int PlayerSquadController.rHitsCount
Referenced by DeselectEnemyes, OnPointerUp, SelectEnemyes.
ContactFilter2D PlayerSquadController.rHitFilter
Referenced by SelectEnemyes, Start.
int PlayerSquadController.rHitLayer
Referenced by Start.
bool PlayerSquadController.mouseDown
Referenced by OnPointerDown, OnPointerUp, Update.
int PlayerSquadController.touchId
Referenced by OnPointerDown, OnPointerUp, Update.
void PlayerSquadController.Awake()
References Instance.
void PlayerSquadController.Start()
References cosAngles, CreateSinCosAngles, Squad.fraction, ground, lineRenderer, maxHitsCount, Squad.playerSquadInstance, rHitCirclreAngle, rHitCirclreSegmentCount, rHitCirclreSegments, rHitFilter, rHitLayer, rHits, sinAngles, squad.
void PlayerSquadController.Update()
References CreatePoints, Squad.CurrentFormation, lookPosition, mouseDown, movePosition, rHitCirclreSegmentCount, rHitCirclreSegments, squad, touchId.
void PlayerSquadController.CreateSinCosAngles()
References cosAngles, rHitCirclreAngle, rHitCirclreSegmentCount, sinAngles.
Referenced by Start.
void PlayerSquadController.CreatePoints()
References cicleCastRadius, cosAngles, rHitCirclreSegmentCount, rHitCirclreSegments, sinAngles.
Referenced by Update.
void PlayerSquadController.SetStartPosition()
References Squad.FlipRotation, movePosition, Squad.PositionsTransform, squad.
Referenced by OnPointerUp.
void PlayerSquadController.SelectEnemyes()
References cicleCastRadius, DeselectEnemyes, movePosition, rHitFilter, rHits, rHitsCount.
Referenced by OnPointerUp.
void PlayerSquadController.FindPath()
References MapBlock.BLOCK_SCALE, endFindPath, lookRotation, movePosition, path, startFindPath.
Referenced by OnPointerUp.
IEnumerator PlayerSquadController.CircleCastConstrict()
References cicleCastRadius, circleConstrincGuaranteeUnits, circleConstrincInPercent, circleExpandDeltaTime, circleExpandDurationInSec, circleMinRadius, coroutineAlive.
Referenced by OnPointerUp.
void PlayerSquadController.DeselectEnemyes()
References rHits, rHitsCount.
Referenced by SelectEnemyes.
void PlayerSquadController.OnPointerDown(PointerEventData eventData)
References Squad.Charging, GameManager.GamePaused, GameManager.Instance, lookPosition, mouseDown, movePosition, squad, touchId.
void PlayerSquadController.OnPointerUp(PointerEventData eventData)
References MapBlock.BLOCK_SCALE, Squad.Charging, CircleCastConstrict, Ground.ColCountOfBlocks, Squad.CurrentFormation, endFindPath, FindPath, GameManager.GamePaused, Ground.Grid, ground, GameManager.Instance, lookPosition, lookRotation, lookVectorDistanse, mouseDown, movePosition, path, Squad.PositionsTransform, rHitsCount, Ground.RowCountOfBlocks, SelectEnemyes, SetStartPosition, squad, startFindPath, thread, touchId, MapBlock.WORLD_BLOCK_SIZE.