NumberConverter
ConvertType
const string NumberConverter.format
Referenced by OnSliderValChanged, SetMaxValues.
TextMeshProUGUI NumberConverter.textValueConfertFrom
TextMeshProUGUI NumberConverter.textValueConvertTo
TextMeshProUGUI NumberConverter.textCurrentValueSelected
TextMeshProUGUI NumberConverter.textCurrentValueConvertedSelected
Slider NumberConverter.slider
Button NumberConverter.btnOk
int NumberConverter.valueConvertTo
Referenced by Convert.
float NumberConverter.convertedValue
Referenced by OnSliderValChanged.
Action NumberConverter.OnCliclOk
Referenced by OnApply.
float NumberConverter.InputValue
Referenced by HospitalRoom.ResetConverter.
float NumberConverter.OutputValue
Referenced by HospitalRoom.Converter_OnCliclOk, HospitalRoom.ResetConverter.
void NumberConverter.Start()
References OnApply, OnSliderValChanged.
void NumberConverter.OnApply()
References OnCliclOk.
Referenced by Start.
void NumberConverter.OnSliderValChanged(float val)
References Convert, convertedValue, format.
Referenced by Start.
float NumberConverter.Convert(float val)
References valueConvertTo.
Referenced by OnSliderValChanged.
void NumberConverter.SetMaxValues(float minValue, float maxValue)
References format.