ConfirmPanel
Text ConfirmPanel.header
Referenced by Show.
Text ConfirmPanel.info
Referenced by Show.
Button ConfirmPanel.buttonYes
Button ConfirmPanel.buttonNo
CanvasGroup ConfirmPanel.cg
Referenced by Awake.
Action ConfirmPanel.OnYes
Referenced by OnPresYes, Show.
ConfirmPanel ConfirmPanel.Instance
Referenced by Awake.
void ConfirmPanel.Awake()
References cg, Instance, OnPresNo, OnPresYes.
void ConfirmPanel.OnPresYes()
References Hide, OnYes.
Referenced by Awake.
void ConfirmPanel.OnPresNo()
References Hide.
Referenced by Awake.
void ConfirmPanel.Show(string header, string info, Action onPressYes=null)
References header, info, OnYes.
void ConfirmPanel.Hide()
Referenced by OnPresNo, OnPresYes.