Stakes
Damage Stakes.damage
Referenced by HitUnit, OnCollisionEnter2D, OnCollisionStay2D.
float Stakes.damagingTickRate
время между активациями нанесения урона по стоящим юнитам
Referenced by Start, SwitchDamaging.
float Stakes.damagingDuration
время продолжительности нанесения урона по стоящим юнитам
Referenced by Start, SwitchDamaging.
Durabilityable Stakes.durabilityble
Referenced by HitUnit, Start.
Collider2D [] Stakes.colliders
Referenced by HitUnit, Start.
bool Stakes.canDamage
Referenced by OnCollisionStay2D, SwitchDamaging.
void Stakes.Start()
References colliders, damagingDuration, damagingTickRate, durabilityble, SwitchDamaging.
IEnumerator Stakes.SwitchDamaging()
References canDamage, damagingDuration, damagingTickRate.
Referenced by Start.
void Stakes.OnCollisionEnter2D(Collision2D collision)
References damage, HitUnit.
void Stakes.OnCollisionStay2D(Collision2D collision)
References canDamage, damage, HitUnit.
void Stakes.HitUnit(Unit unit, Damage damage)
References Damage.BaseDamage, colliders, damage, durabilityble, Durabilityable.TakeDamage.
Referenced by OnCollisionEnter2D, OnCollisionStay2D.