PopUpTextController
GameObject [] PopUpTextController.textOrigin
Referenced by GetText.
Vector2 PopUpTextController.floatSpeed
Referenced by AddTextLabel, PopUpTextController.PopUpTextProperties.PopUpTextProperties.
float PopUpTextController.textLifeTime
Referenced by AddTextLabel.
Color PopUpTextController.startColor
Referenced by AddTextLabel.
Color PopUpTextController.endColor
Referenced by AddTextLabel.
Transform PopUpTextController.thisTransform
Referenced by Awake, GetText.
List<Item> PopUpTextController.textes
Referenced by PopUpTexts.
Stack<TextMeshPro> PopUpTextController.pool
Referenced by GetText, Start.
Camera PopUpTextController.mainCamera
Referenced by Start.
PopUpTextController PopUpTextController.Instance
Referenced by Awake, Unit.ShowPopUpTakenDamageText.
void PopUpTextController.Awake()
References Instance, thisTransform.
void PopUpTextController.Start()
References GetText, GiveBackText, mainCamera, pool.
void PopUpTextController.Update()
References PopUpTexts.
void PopUpTextController.PopUpTexts()
References GiveBackText, textes.
Referenced by Update.
void PopUpTextController.AddTextLabel(string text, Vector2 worldPosition, float?lifetime=null, Vector2?screenFloatSpeed=null, Color?startColor=null, Color?endColor=null, int sortingOrder=0, float?fontSize=null)
References endColor, floatSpeed, GetText, startColor, textLifeTime.
Referenced by Unit.ShowPopUpTakenDamageText.
TextMeshPro PopUpTextController.GetText(int index=0)
References pool, textOrigin, thisTransform.
Referenced by AddTextLabel, Start.
void PopUpTextController.GiveBackText(TextMeshPro text)
Referenced by PopUpTexts, Start.