UnityEngine::RuleTile
Sprite UnityEngine.RuleTile.m_DefaultSprite
Referenced by UnityEngine.RuleTile.GetTileData.
Tile.ColliderType UnityEngine.RuleTile.m_DefaultColliderType
Referenced by UnityEngine.RuleTile.GetTileData.
List<TilingRule> UnityEngine.RuleTile.m_TilingRules
Referenced by UnityEngine.RuleTile.GetTileAnimationData, UnityEngine.RuleTile.GetTileData, UnityEngine.RuleTile.RefreshTile.
override void UnityEngine.RuleTile.GetTileData(Vector3Int position, ITilemap tileMap, ref TileData tileData)
References UnityEngine.RuleTile.ApplyRandomTransform, UnityEngine.RuleTile.GetPerlinValue, UnityEngine.RuleTile.m_DefaultColliderType, UnityEngine.RuleTile.m_DefaultSprite, UnityEngine.RuleTile.TilingRule.m_Output, UnityEngine.RuleTile.TilingRule.m_PerlinScale, UnityEngine.RuleTile.TilingRule.m_RandomTransform, UnityEngine.RuleTile.TilingRule.m_Sprites, UnityEngine.RuleTile.m_TilingRules, UnityEngine.RuleTile.RuleMatches.
override bool UnityEngine.RuleTile.GetTileAnimationData(Vector3Int position, ITilemap tilemap, ref TileAnimationData tileAnimationData)
References UnityEngine.RuleTile.TilingRule.m_Output, UnityEngine.RuleTile.m_TilingRules, UnityEngine.RuleTile.RuleMatches.
override void UnityEngine.RuleTile.RefreshTile(Vector3Int location, ITilemap tileMap)
References UnityEngine.RuleTile.m_TilingRules.
bool UnityEngine.RuleTile.RuleMatches(TilingRule rule, Vector3Int position, ITilemap tilemap, ref Matrix4x4 transform)
References UnityEngine.RuleTile.TilingRule.m_RuleTransform.
Referenced by UnityEngine.RuleTile.GetTileAnimationData, UnityEngine.RuleTile.GetTileData.
bool UnityEngine.RuleTile.RuleMatches(TilingRule rule, Vector3Int position, ITilemap tilemap, int angle)
References UnityEngine.RuleTile.GetIndexOfOffset, UnityEngine.RuleTile.GetRotatedPos, UnityEngine.RuleTile.TilingRule.m_Neighbors.
bool UnityEngine.RuleTile.RuleMatches(TilingRule rule, Vector3Int position, ITilemap tilemap, bool mirrorX, bool mirrorY)
References UnityEngine.RuleTile.GetIndexOfOffset, UnityEngine.RuleTile.GetMirroredPos, UnityEngine.RuleTile.TilingRule.m_Neighbors.
Vector3Int UnityEngine.RuleTile.GetRotatedPos(Vector3Int original, int rotation)
Referenced by UnityEngine.RuleTile.RuleMatches.
Vector3Int UnityEngine.RuleTile.GetMirroredPos(Vector3Int original, bool mirrorX, bool mirrorY)
Referenced by UnityEngine.RuleTile.RuleMatches.
static float UnityEngine.RuleTile.GetPerlinValue(Vector3Int position, float scale, float offset)
Referenced by UnityEngine.RuleTile.ApplyRandomTransform, UnityEngine.RuleTile.GetTileData.
static Matrix4x4 UnityEngine.RuleTile.ApplyRandomTransform(TilingRule.Transform type, Matrix4x4 original, float perlinScale, Vector3Int position)
References UnityEngine.RuleTile.GetPerlinValue.
Referenced by UnityEngine.RuleTile.GetTileData.
int UnityEngine.RuleTile.GetIndexOfOffset(Vector3Int offset)
Referenced by UnityEngine.RuleTile.RuleMatches.