EnvirinmantInventoryUI
EnvirinmantInventoryUI EnvirinmantInventoryUI.Instance
Referenced by Awake, ADropToMe.RefreshUI.
int EnvirinmantInventoryUI.RadiusToFind
bool EnvirinmantInventoryUI.Fill
GameObject EnvirinmantInventoryUI.inventoryItemOriginal
Referenced by SetImage.
Transform EnvirinmantInventoryUI.envaironmentInventory
Referenced by Awake.
Transform [] EnvirinmantInventoryUI.envaironmentCells
Referenced by Awake, ClearEnvironmantInventoryIcons, FillEnvironmantInventoryIcons.
int EnvirinmantInventoryUI.maxRhitsCount
Referenced by Start.
int EnvirinmantInventoryUI.radiusToFind
Referenced by CreatePoints, FindItems, OnDrawGizmos.
float EnvirinmantInventoryUI.delayBeforeDrawPickUpArea
Referenced by DrawPickUpArea.
float EnvirinmantInventoryUI.rHitCirclreAngle
Referenced by CreateSinCosAngles, Start.
List<EquipmentStack> EnvirinmantInventoryUI.inventory
Referenced by Awake, FillEnvironmantInventoryIcons, FillInventory, FindItems.
RaycastHit2D [] EnvirinmantInventoryUI.rhits
Referenced by FindItems, PickUpEquipment, Start.
ContactFilter2D EnvirinmantInventoryUI.rHitFilter
Referenced by FindItems, Start.
int EnvirinmantInventoryUI.hitCount
Referenced by FindItems, PickUpEquipment.
LineRenderer EnvirinmantInventoryUI.lineRenderer
Referenced by Start.
int EnvirinmantInventoryUI.rHitCirclreSegmentCount
Referenced by CreatePoints, CreateSinCosAngles, Start, Update.
Vector3 [] EnvirinmantInventoryUI.rHitCirclreSegments
Referenced by CreatePoints, Start, Update.
float [] EnvirinmantInventoryUI.sinAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
float [] EnvirinmantInventoryUI.cosAngles
Referenced by CreatePoints, CreateSinCosAngles, Start.
bool EnvirinmantInventoryUI.toggleDown
Referenced by ContentToggle_OnDown, ContentToggle_OnUp, DrawPickUpArea, Update.
bool EnvirinmantInventoryUI.draw
Referenced by ContentToggle_OnUp, DrawPickUpArea, Update.
bool EnvirinmantInventoryUI.canRefresh
Referenced by RefreshOnUnitDeath, WaitForRefresh.
float EnvirinmantInventoryUI.timeToRefresh
Referenced by WaitForRefresh.
void EnvirinmantInventoryUI.Awake()
References envaironmentCells, envaironmentInventory, Instance, inventory.
void EnvirinmantInventoryUI.Start()
References cosAngles, CreateSinCosAngles, lineRenderer, maxRhitsCount, RefreshOnUnitDeath, rHitCirclreAngle, rHitCirclreSegmentCount, rHitCirclreSegments, rHitFilter, rhits, sinAngles.
void EnvirinmantInventoryUI.OnDestroy()
References RefreshOnUnitDeath.
void EnvirinmantInventoryUI.RefreshOnUnitDeath()
References canRefresh, WaitForRefresh.
Referenced by OnDestroy, Start.
IEnumerator EnvirinmantInventoryUI.WaitForRefresh()
References canRefresh, RefreshUI, timeToRefresh.
Referenced by RefreshOnUnitDeath.
void EnvirinmantInventoryUI.Update()
References CreatePoints, draw, rHitCirclreSegmentCount, rHitCirclreSegments, toggleDown.
IEnumerator EnvirinmantInventoryUI.DrawPickUpArea()
References delayBeforeDrawPickUpArea, draw, toggleDown.
Referenced by ContentToggle_OnDown.
void EnvirinmantInventoryUI.CreateSinCosAngles()
References cosAngles, rHitCirclreAngle, rHitCirclreSegmentCount, sinAngles.
Referenced by Start.
void EnvirinmantInventoryUI.CreatePoints()
References cosAngles, radiusToFind, rHitCirclreSegmentCount, rHitCirclreSegments, sinAngles.
Referenced by Update.
void EnvirinmantInventoryUI.FillEnvironmantInventoryIcons()
References envaironmentCells, inventory, SetImage.
Referenced by RefreshUI.
void EnvirinmantInventoryUI.ClearEnvironmantInventoryIcons()
References envaironmentCells.
Referenced by RefreshUI.
void EnvirinmantInventoryUI.OnDrawGizmos()
References Squad.playerSquadInstance, radiusToFind.
void EnvirinmantInventoryUI.ContentToggle_OnUp()
References draw, toggleDown.
void EnvirinmantInventoryUI.ContentToggle_OnDown()
References DrawPickUpArea, toggleDown.
void EnvirinmantInventoryUI.FillInventory(EquipmentStack stack)
References inventory.
Referenced by FindItems.
void EnvirinmantInventoryUI.PickUpEquipment(EquipmentStack stack)
References EquipmentStack.Count, EquipmentStack.EquipmentStats, hitCount, EquipmentStats.Id, EquipmentStats.ItemDurability, rhits, DroppedItem.Stack, EquipmentStats.Type.
void EnvirinmantInventoryUI.FindItems()
References FillInventory, hitCount, inventory, radiusToFind, rHitFilter, rhits, DroppedItem.Stack.
Referenced by RefreshUI.
void EnvirinmantInventoryUI.SetImage(Transform cell, EquipmentStack stack, bool canDrag)
References inventoryItemOriginal.
Referenced by FillEnvironmantInventoryIcons.
void EnvirinmantInventoryUI.RefreshUI()
References ClearEnvironmantInventoryIcons, FillEnvironmantInventoryIcons, FindItems.
Referenced by WaitForRefresh.