HealthBar
Image HealthBar.targetGraphix
Referenced by Start.
RectTransform HealthBar.targetGraphixTransform
Referenced by Start.
Text HealthBar.textHp
Text HealthBar.textCount
Squad HealthBar.playerSquad
Referenced by OnDestroy, Start.
void HealthBar.Start()
References DrawCountUnits, DrawHpBar, Squad.OnSumHealthChanged, Squad.OnUitCountChanged, playerSquad, Squad.playerSquadInstance, Squad.SquadHealth, targetGraphix, targetGraphixTransform, Squad.UnitCount.
void HealthBar.DrawCountUnits(int newCount)
Referenced by OnDestroy, Start.
void HealthBar.OnDestroy()
References DrawCountUnits, DrawHpBar, playerSquad.
void HealthBar.DrawHpBar(float squadHealth)
Referenced by OnDestroy, Start.