StatsUpgrade
StatName
TextMeshProUGUI StatsUpgrade.name
TextMeshProUGUI StatsUpgrade.currentValue
TextMeshProUGUI StatsUpgrade.additionalValue
TextMeshProUGUI StatsUpgrade.cost
Slider StatsUpgrade.sliderToNextLevel
Slider StatsUpgrade.sliderToHightestLevel
StatName StatsUpgrade.statName
Referenced by ResetStat, SetValues.
AnimationCurve StatsUpgrade.upgradeCost
Referenced by SetValues.
int StatsUpgrade.uprgadeLevelsCount
Referenced by SetValues.
float StatsUpgrade.minCost
Referenced by SetValues.
float StatsUpgrade.maxCost
Referenced by SetValues.
Button StatsUpgrade.btn
Referenced by Awake.
DSUnitStats.Stat StatsUpgrade.stat
Referenced by OnClick, SetValues.
float StatsUpgrade.nextLevelCost
Referenced by OnClick, SetValues.
float StatsUpgrade.nextLevelCostWhenProgressZero
Referenced by OnClick, SetValues.
float StatsUpgrade.additionnalVal
Referenced by OnClick, SetValues.
void StatsUpgrade.Awake()
References btn, OnClick.
void StatsUpgrade.Start()
References SetValues.
void StatsUpgrade.SetValues()
References additionnalVal, Localization.attack, Localization.defence, Localization.health, maxCost, minCost, nextLevelCost, nextLevelCostWhenProgressZero, Localization.rotationSpeed, Localization.speed, stat, statName, upgradeCost, uprgadeLevelsCount.
Referenced by OnClick, ResetStat, Start.
void StatsUpgrade.OnClick()
References additionnalVal, DSPlayerScore.expirience, nextLevelCost, nextLevelCostWhenProgressZero, SetValues, stat, Localization.toast_not_enough_expirience, Localization.toast_stat_max_upgrade, DSPlayerScore.Score.Value.
Referenced by Awake.
void StatsUpgrade.ResetStat()
References SetValues, statName.