TintTextureGenerator
int TintTextureGenerator.k_TintMapSize
Referenced by RefreshGlobalShaderValues.
Texture2D TintTextureGenerator.m_TintTexture
Referenced by RefreshGlobalShaderValues.
Texture2D TintTextureGenerator.tintTexture
Referenced by TextureToWorld, WorldToTexture.
void TintTextureGenerator.Start()
References Refresh.
void TintTextureGenerator.Refresh(Grid grid)
References GetGridInformation, TextureToWorld.
Referenced by SetColor, Start.
void TintTextureGenerator.Refresh(Grid grid, Vector3Int position)
References GetGridInformation, RefreshGlobalShaderValues, WorldToTexture.
Color TintTextureGenerator.GetColor(Grid grid, Vector3Int position)
References UnityEngine.Tilemaps.Color, GetGridInformation.
void TintTextureGenerator.SetColor(Grid grid, Vector3Int position, Color color)
References GetGridInformation, Refresh.
Vector3Int TintTextureGenerator.WorldToTexture(Vector3Int world)
References tintTexture.
Referenced by Refresh.
Vector3Int TintTextureGenerator.TextureToWorld(Vector3Int texpos)
References tintTexture.
Referenced by Refresh.
GridInformation TintTextureGenerator.GetGridInformation(Grid grid)
Referenced by GetColor, Refresh, SetColor.
void TintTextureGenerator.RefreshGlobalShaderValues()
References k_TintMapSize, m_TintTexture.
Referenced by Refresh.