Squad
UnitFraction
Squad Squad.playerSquadInstance
Referenced by DropToEquipment.AddToThisInventory, DropToInventory.AddToThisInventory, Unit.AfterTakingDamage, Awake, Unit.CheckToUnion, GameManager.InitPlayer, GameManager.LoadMainMenu, SkillButton.OnBeginDrag, DeathScreen.OnDestroy, StatsPanelUI.OnDestroy, SquadInventoryUI.OnDestroy, SkillButton.OnDrag, EnvirinmantInventoryUI.OnDrawGizmos, DropToEquipment.OnDrop, HospitalRoom.OnEnable, SkillButton.OnEndDrag, StatsPanelUI.OnEquipmentChanged, SkillButton.OnPointerClick, ShowAllyUnitsHp.OnPointerDown, ShowAllyUnitsHp.OnPointerUp, SquadInventoryUI.RefreshUI, DropToInventory.RemoveFromThisInventory, SquadCerrentProp.Start, HealthBar.Start, FormationButton.Start, PlayerSquadPathFinderController.Start, PlayerSquadController.Start, Start, ShowAllyUnitsHp.StopDrawing, Unit.TakeHitFromArrow, UnitDeath.
Transform Squad.minimapMark
Referenced by Start, Update.
Unit Squad.unitOriginal
Referenced by Start.
UnitStats Squad.unitStats
Referenced by SetUnitsStats.
int Squad.fullSquadUnitCount
Referenced by Awake.
int Squad.squadLength
Referenced by Awake, FlipPhalanx, ReformSquadInPhalanx, ReformSquadInRanks.
int Squad.squadRowsMax
Referenced by Awake.
float Squad.maxSpeed
Referenced by CalcSpeed, SetUnitsStats.
float Squad.maxRotationSpeed
Referenced by CalcSpeed.
float Squad.rotationAcuracy
Referenced by MovingInPhalanx, MovingInRanks.
float Squad.positionAcuracy
Referenced by MovingInPhalanx, MovingInRanks.
FormationStats.Formations Squad.formation
FormationStats Squad.currentFormationModifyers
float Squad.delayToGetOutOfTheFight
Referenced by SetFlagFight.
float Squad.distanceToUnionWithSquad
Referenced by OnDrawGizmos.
Inventory Squad.inventory
Referenced by SetProp, Start.
float Squad.currentSpeed
Referenced by CalcSpeed, WaitForEndGharge.
float Squad.currentRotationSpeed
Referenced by CalcSpeed, LookTo.
bool Squad.flipRotation
Referenced by AddUnit, FlipPhalanx, LookWithoutFullRotation, UnitDeath.
int Squad.attakingUnitsCount
Referenced by OlreadyNotInFight, SetFlagFight.
int Squad.targettedUnitsCount
Referenced by OlreadyNotInFight, SetFlagFight.
Vector2 Squad.centerSquad
Referenced by DrawPath, OnDrawGizmos, SumPositionUnit, Update.
List<UnitPosition> Squad.unitPositions
Referenced by AddUnitWithoutReformSquad, Awake, FlipPhalanx, ReformSquadInPhalanx, ReformSquadInRanks, SetUnitsStats, SumPositionUnit, UnitDeath.
bool Squad.inFight
Referenced by OnDrawGizmos.
float Squad.squadHelth
Referenced by Awake, SetUnitsStats.
List<Vector3> Squad.path
Referenced by DrawPath, GoTo, MovingInPhalanx, MovingInRanks.
Vector3 Squad.endMovePosition
Referenced by GoTo, SetEndMovePositions.
LineRenderer Squad.lineRenderer
Referenced by Awake, DrawPath.
int Squad.pathStep
Referenced by DrawPath, GoTo, MovingInPhalanx, MovingInRanks.
bool Squad.drawUnitHp
bool Squad.charging
Referenced by WaitForEndGharge.
float Squad.sumX
Referenced by SumPositionUnit.
float Squad.sumY
Referenced by SumPositionUnit.
int Squad.countSumUnit
Referenced by SumPositionUnit.
UnitStats Squad.UnitStats
Referenced by StatsPanelUI.OnEquipmentChanged.
int Squad.FULL_SQUAD_UNIT_COUNT
Referenced by Awake, Unit.CheckToUnion, ReformSquadInPhalanx, Start.
int Squad.SQUAD_LENGTH
Referenced by ReformSquadInPhalanx, ReformSquadInRanks.
int Squad.SQUAD_ROWS_MAX
float Squad.MaxSpeed
float Squad.MaxRotationSpeed
float Squad.RotationAcuracy
float Squad.PositionAcuracy
FormationStats.Formations Squad.CurrentFormation
Referenced by Unit.AfterTakingDamage, SkillCharge.DoSkill, Unit.FindTarget, Unit.Init, Moving, Unit.Moving, Unit.OnFormationChanged, PlayerSquadPathFinderController.OnPointerUp, FormationButton.OnPointerUp, PlayerSquadController.OnPointerUp, Unit.OnPushEnd, Unit.OnPushStart, FormationButton.PlayerSquadInstance_OnFormationChanged, ReformSquad, SetProp, SquadCerrentProp.Start, FormationButton.Start, Start, Unit.TakeHitFromArrow, Unit.TakeHitFromUnit, PlayerSquadController.Update.
FormationStats Squad.CurrentFormationModifyers
float Squad.DistanceToUnionWithSquad
Referenced by Unit.CheckToUnion.
Inventory Squad.Inventory
Referenced by DropToEquipment.AddToThisInventory, DropToInventory.AddToThisInventory, Unit.CheckEquipment, Unit.Death, SquadInventoryUI.RefreshUI, DropToInventory.RemoveFromThisInventory, Unit.SetEquipment, Unit.TakeHitFromArrow.
float Squad.CurrentSpeed
Referenced by MoveTo.
float Squad.CurrentRotationSpeed
bool Squad.FlipRotation
Referenced by LookWithoutFullRotation, AiSquadController.SetStartPosition, PlayerSquadController.SetStartPosition.
int Squad.AttakingUnitsCount
int Squad.TargettedUnitsCount
Vector2 Squad.CenterSquad
Referenced by Exit.CheckCenterSquadToExit, CameraController.Update.
List<UnitPosition> Squad.UnitPositions
! , ?!
bool Squad.InFight
Referenced by Unit.CheckToUnion, OlreadyNotInFight, Unit.OnPushStart, SetFlagFight.
GameObject Squad.UnitsContainer
Referenced by Awake.
int Squad.UnitCount
Referenced by Unit.CheckToUnion, Unit.Death, DropToEquipment.OnDrop, StatsPanelUI.OnEquipmentChanged, SetProp, HealthBar.Start.
float Squad.SquadHealth
Referenced by AddUnitWithoutReformSquad, SetUnitsStats, HealthBar.Start.
Transform Squad.PositionsTransform
Referenced by AddUnitWithoutReformSquad, Awake, CheckPositionInRange, AiSquadController.GoTo, GameManager.InitPlayer, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp, AiSquadController.SetStartPosition, PlayerSquadController.SetStartPosition, AiSquadController.SquadAttack, Start.
bool Squad.DrawUnitHp
Referenced by ShowAllyUnitsHp.OnPointerDown.
bool Squad.Charging
Referenced by PlayerSquadPathFinderController.OnPointerDown, PlayerSquadController.OnPointerDown, PlayerSquadPathFinderController.OnPointerUp, PlayerSquadController.OnPointerUp.
UnitFraction Squad.fraction
Referenced by AddUnitWithoutReformSquad, PlayerSquadController.Start.
Quaternion Squad.endLookRotation
Referenced by MovingInPhalanx, Unit.MovingInPhalanx, MovingInRanks, SetEndMovePositions, Start.
Action<bool> Squad.OnInFightFlagChanged
Action<int> Squad.OnUitCountChanged
Referenced by AddUnitWithoutReformSquad, HealthBar.Start, UnitDeath.
Action<float> Squad.OnSumHealthChanged
Referenced by HealthBar.Start.
Action<FormationStats.Formations> Squad.OnFormationChanged
Referenced by Start.
Action<EquipmentStack> Squad.OnDropStackFromInventory
Referenced by DropEquipment.
Action<FormationStats.Formations> Squad.OnReformSquad
Referenced by ReformSquad.
Action Squad.OnInitiateUnitPositions
Referenced by ResetUnitPositions.
Action<float, float> Squad.OnBeginCharge
- .
- .
Referenced by WaitForEndGharge.
Action<float, float> Squad.OnEndCharge
- .
- .
Referenced by WaitForEndGharge.
Action<UnitStats, UnitStats> Squad.OnUnitStatsChanged
Referenced by SetUnitsStats.
Action<bool> Squad.OnDrawUnitHpChanged
Action Squad.OnSquadDestroy
Referenced by UnitDeath.
void Squad.Awake()
References FULL_SQUAD_UNIT_COUNT, fullSquadUnitCount, lineRenderer, playerSquadInstance, PositionsTransform, squadHelth, squadLength, squadRowsMax, unitPositions, UnitsContainer.
void Squad.Start()
References AddUnitWithoutReformSquad, CurrentFormation, endLookRotation, FULL_SQUAD_UNIT_COUNT, inventory, LookWithoutFullRotation, minimapMark, OnFormationChanged, playerSquadInstance, PositionsTransform, SetProp, SetUnitsStats, unitOriginal, Inventory.Weapon.
void Squad.Update()
References centerSquad, DrawPath, minimapMark, Moving.
void Squad.CalcSpeed()
!!! ,
References currentRotationSpeed, currentSpeed, maxRotationSpeed, maxSpeed.
Referenced by SetProp, SetUnitsStats.
void Squad.SetProp(Equipment newEquipment=null)
References CalcSpeed, EquipmentStats.CanUseWithShield, CurrentFormation, DropEquipment, EquipmentStats.Empty, inventory, Inventory.Shield, Equipment.Stats, UnitCount, Inventory.Weapon.
Referenced by Start.
void Squad.SetFlagFight()
References attakingUnitsCount, delayToGetOutOfTheFight, InFight, OlreadyNotInFight, targettedUnitsCount.
IEnumerator Squad.OlreadyNotInFight(float duration)
References attakingUnitsCount, InFight, targettedUnitsCount.
Referenced by SetFlagFight.
IEnumerator Squad.WaitForEndGharge(float addSpeed, float addAcceleration, float duration)
References charging, currentSpeed, OnBeginCharge, OnEndCharge.
Referenced by Charge.
void Squad.Moving()
References CurrentFormation, MovingInPhalanx, MovingInRanks, MovingInRiseshields.
Referenced by Update.
void Squad.MovingInRiseshields()
References MovingInRanks.
Referenced by Moving.
void Squad.MovingInPhalanx()
References CheckPositionInRange, CheckRotationInRange, endLookRotation, LookWithoutFullRotation, MoveTo, path, pathStep, positionAcuracy, rotationAcuracy.
Referenced by Moving.
void Squad.MovingInRanks()
References CalcTargetRotations, CheckPositionInRange, CheckRotationInRange, endLookRotation, LookWithoutFullRotation, MoveTo, path, pathStep, positionAcuracy, rotationAcuracy.
Referenced by Moving, MovingInRiseshields.
void Squad.DrawPath()
LineRenderer,
References centerSquad, lineRenderer, path, pathStep.
Referenced by Update.
void Squad.LookWithoutFullRotation(Quaternion lookRot)
, . . lookRot
References flipRotation, FlipRotation, LookTo, ReformSquad.
Referenced by MovingInPhalanx, MovingInRanks, Start.
void Squad.AddUnitWithoutReformSquad(Unit unit)
. .
unit
References fraction, OnUitCountChanged, PositionsTransform, SquadHealth, unitPositions.
Referenced by AddUnit, Start.
void Squad.FlipPhalanx()
, .
References flipRotation, ReformSquad, squadLength, unitPositions.
void Squad.ReformSquad(bool flipRotation, UnitPosition objToRemove=null)
,
flipRotation objToRemove ,
References CurrentFormation, OnReformSquad, ReformSquadInPhalanx, ReformSquadInRanks.
Referenced by AddUnit, FlipPhalanx, LookWithoutFullRotation, UnitDeath.
void Squad.ReformSquadInRanks(bool flipRotation, UnitPosition objToRemove)
References SQUAD_LENGTH, squadLength, unitPositions.
Referenced by ReformSquad.
void Squad.ReformSquadInPhalanx(bool flipRotation, UnitPosition objToRemove)
References FULL_SQUAD_UNIT_COUNT, UnitPosition.PositionInArray, SQUAD_LENGTH, squadLength, unitPositions.
Referenced by ReformSquad.
Quaternion Squad.CalcTargetRotations(Vector3 targetPosition)
Referenced by MovingInRanks.
bool Squad.CheckRotationInRange(Quaternion targetRotation, float rotationRange)
Referenced by MovingInPhalanx, MovingInRanks.
bool Squad.CheckPositionInRange(Vector2 position, float positionRange)
References PositionsTransform.
Referenced by MovingInPhalanx, MovingInRanks.
void Squad.LookTo(Quaternion lookRotation)
References currentRotationSpeed.
Referenced by LookWithoutFullRotation.
void Squad.MoveTo(Vector2 position)
References CurrentSpeed.
Referenced by MovingInPhalanx, MovingInRanks.
void Squad.OnDrawGizmos()
References centerSquad, distanceToUnionWithSquad, inFight.
void Squad.SetUnitsStats(DSUnitStats stats)
References CalcSpeed, maxSpeed, OnUnitStatsChanged, SquadHealth, squadHelth, unitPositions, unitStats.
Referenced by Start.
void Squad.Charge(float addSpeed, float addAcceleration, float duration)
References WaitForEndGharge.
void Squad.SumPositionUnit(Unit unit)
, . Update unit
References centerSquad, countSumUnit, sumX, sumY, unitPositions.
void Squad.AddUnit(Unit unit)
. .
unit
References AddUnitWithoutReformSquad, flipRotation, ReformSquad.
void Squad.UnitDeath(Unit unit)
. .
unitPositionObject
References flipRotation, OnSquadDestroy, OnUitCountChanged, playerSquadInstance, ReformSquad, Unit.TargetMovePositionObject, unitPositions.
void Squad.ResetUnitPositions()
References OnInitiateUnitPositions.
void Squad.SetEndMovePositions(Vector3 positionMove, Quaternion rotationLook)
positionMove rotationLook
References endLookRotation, endMovePosition.
void Squad.GoTo(List< Vector3 > path)
path
References endMovePosition, path, pathStep.
void Squad.DropEquipment(EquipmentStack stack)
.
stack
References OnDropStackFromInventory.
Referenced by SetProp.