ArrowsValley
ParticleSystem ArrowsValley.realValleyParticleSystem
Referenced by Awake, DestroyValleyObject, Init, WAitForWarningValley.
ParticleSystem ArrowsValley.warningValleyParticleSystem
Referenced by Awake, Init, StartValley.
List<ParticleSystem.Particle> ArrowsValley.trigPartc
Referenced by Awake, RealValley, WarningValley.
List<ParticleSystem.Particle> ArrowsValley.stayingParticles
int ArrowsValley.layerMask
Referenced by Awake, RealValley, WarningValley.
Unit ArrowsValley.unit
Referenced by RealValley, WarningValley.
RaycastHit2D ArrowsValley.rhit
Referenced by RealValley, WarningValley.
float ArrowsValley.dalayBeforeWarningValley
Referenced by StartValley.
Transform ArrowsValley.endPoint
Referenced by Init.
LayerMask ArrowsValley.raycastTargetLayers
string ArrowsValley.PROFILING_NAME
Referenced by OnParticleTrigger.
Damage ArrowsValley.damage
Referenced by RealValley, WarningValley.
Squad ArrowsValley.owner
Referenced by Init, Unit.TakeHitFromArrow.
void ArrowsValley.Awake()
References layerMask, realValleyParticleSystem, trigPartc, warningValleyParticleSystem.
void ArrowsValley.Start()
References DestroyValleyObject.
IEnumerator ArrowsValley.DestroyValleyObject()
References realValleyParticleSystem.
Referenced by Start.
IEnumerator ArrowsValley.WAitForWarningValley(float time)
References GoToLowLevelRendering, realValleyParticleSystem.
Referenced by StartValley.
IEnumerator ArrowsValley.GoToLowLevelRendering(ParticleSystem pSys, float time)
Referenced by StartValley, WAitForWarningValley.
void ArrowsValley.OnParticleTrigger()
References PROFILING_NAME, RealValley.
void ArrowsValley.WarningValley()
References damage, layerMask, rhit, trigPartc, unit.
void ArrowsValley.RealValley()
References damage, layerMask, rhit, trigPartc, unit.
Referenced by OnParticleTrigger.
void ArrowsValley.Init(Vector2 position, Damage damage, float radius, int countOfArrows, Squad owner=null)
References endPoint, owner, realValleyParticleSystem, warningValleyParticleSystem.
void ArrowsValley.StartValley()
References dalayBeforeWarningValley, GoToLowLevelRendering, WAitForWarningValley, warningValleyParticleSystem.