UnitAnimationController
EquipmentIndex
UnitOutline UnitAnimationController.underlayerOutline
Referenced by Death, Outline.
new SpriteRenderer [] UnitAnimationController.renderer
Referenced by Death, SetAnimationStates, SetNewEquipment.
new UnitAnimation [] UnitAnimationController.animation
Referenced by Death, SetAnimationStates, SetNewEquipment.
SpriteOutline [] UnitAnimationController.outline
Referenced by Death, Outline, SetNewEquipment.
Squad UnitAnimationController.squad
Referenced by OnDestroy, Unit_AfterInitiate.
Unit UnitAnimationController.unit
Referenced by Awake, Death.
FormationStats.Formations UnitAnimationController.formation
Referenced by SetAnimationStates.
bool UnitAnimationController.hit
bool UnitAnimationController.run
Referenced by SetAnimationStates.
bool UnitAnimationController.inFight
Referenced by SetAnimationStates.
FormationStats.Formations UnitAnimationController.Formation
Referenced by Squad_OnFormationChanged.
bool UnitAnimationController.Run
Referenced by Unit_OnRunValueChanged.
bool UnitAnimationController.InFight
Referenced by Squad_OnInFightFlagChanged.
void UnitAnimationController.Awake()
References Unit.Arms, Death, Unit.Legs, unit, Unit_AfterInitiate, Unit_OnArmsChanged, Unit_OnBodyChanged, Unit_OnHelmetChanged, Unit_OnLegsChanged, Unit_OnRunValueChanged, Unit_OnShieldChanged, Unit_OnWeaponChanged.
void UnitAnimationController.Unit_AfterInitiate()
References squad, Squad_OnFormationChanged, Squad_OnInFightFlagChanged.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Squad_OnFormationChanged(FormationStats.Formations value)
References Formation.
Referenced by OnDestroy, Unit_AfterInitiate.
void UnitAnimationController.Squad_OnInFightFlagChanged(bool value)
References InFight.
Referenced by OnDestroy, Unit_AfterInitiate.
void UnitAnimationController.Unit_OnRunValueChanged(bool value)
References Run.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnWeaponChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnShieldChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnLegsChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnHelmetChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnBodyChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.Unit_OnArmsChanged(GameObject obj)
References SetNewEquipment.
Referenced by Awake, OnDestroy.
void UnitAnimationController.SetNewEquipment(EquipmentIndex index, GameObject equipment)
References animation, outline, renderer, SetAnimationStates.
Referenced by Unit_OnArmsChanged, Unit_OnBodyChanged, Unit_OnHelmetChanged, Unit_OnLegsChanged, Unit_OnShieldChanged, Unit_OnWeaponChanged.
void UnitAnimationController.OnDestroy()
References Death, squad, Squad_OnFormationChanged, Squad_OnInFightFlagChanged, Unit_AfterInitiate, Unit_OnArmsChanged, Unit_OnBodyChanged, Unit_OnHelmetChanged, Unit_OnLegsChanged, Unit_OnRunValueChanged, Unit_OnShieldChanged, Unit_OnWeaponChanged.
void UnitAnimationController.Death()
References animation, outline, Outline, renderer, Unit.Shadow, underlayerOutline, unit.
Referenced by Awake, OnDestroy.
void UnitAnimationController.SetAnimationStates()
References animation, formation, inFight, Outline, renderer, run.
Referenced by SetNewEquipment.
void UnitAnimationController.Outline(int itemIndex)
References outline, underlayerOutline.
Referenced by Death, SetAnimationStates.