SettingsGraphixSection
Toggle SettingsGraphixSection.showDamageToggle
Toggle SettingsGraphixSection.allyOutlineToggle
Toggle SettingsGraphixSection.enemyOutlineToggle
Toggle SettingsGraphixSection.neutralOutlineToggle
Toggle SettingsGraphixSection.borderOutline
Toggle SettingsGraphixSection.underlayerOutline
void SettingsGraphixSection.Start()
References ResetPrefsUI.
void SettingsGraphixSection.ResetPrefsUI()
References OnAllyOutlineToggleValChanged, OnBorderOutlineToggleValChanged, OnEnemyOutlineToggleValChanged, OnNeutralOutlineToggleValChanged, OnShowDamageToggleValChanged, OnUnderlayerOutlineToggleValChanged.
Referenced by Start.
void SettingsGraphixSection.OnBorderOutlineToggleValChanged(bool value)
Referenced by ResetPrefsUI.
void SettingsGraphixSection.OnUnderlayerOutlineToggleValChanged(bool value)
Referenced by ResetPrefsUI.
void SettingsGraphixSection.OnShowDamageToggleValChanged(bool value)
Referenced by ResetPrefsUI.
void SettingsGraphixSection.OnAllyOutlineToggleValChanged(bool value)
Referenced by ResetPrefsUI.
void SettingsGraphixSection.OnEnemyOutlineToggleValChanged(bool value)
Referenced by ResetPrefsUI.
void SettingsGraphixSection.OnNeutralOutlineToggleValChanged(bool value)
Referenced by ResetPrefsUI.