DeathScreen
TextMeshProUGUI DeathScreen.headerText
TextMeshProUGUI DeathScreen.tipsText
Image DeathScreen.tipsImage1
Image DeathScreen.tipsImage2
SOTip [] DeathScreen.tips
Referenced by SetTips.
CanvasGroup DeathScreen.cg
Referenced by PlayerSquadInstance_OnSquadDestroy, Start.
void DeathScreen.Start()
References cg, PlayerSquadInstance_OnSquadDestroy.
void DeathScreen.OnDestroy()
References Squad.playerSquadInstance, PlayerSquadInstance_OnSquadDestroy.
void DeathScreen.PlayerSquadInstance_OnSquadDestroy()
References cg, SetTips.
Referenced by OnDestroy, Start.
void DeathScreen.SetTips()
References SOTip.images, tips.
Referenced by PlayerSquadInstance_OnSquadDestroy.