TipsPanel
const int TipsPanel.COUNT_OF_DESC_ITEM
const int TipsPanel.DESCRIPTION
const int TipsPanel.COST
const int TipsPanel.CONSTRAINTS
const int TipsPanel.STATS
Image TipsPanel.itemIcon
CanvasGroup TipsPanel.costPanel
TextMeshProUGUI TipsPanel.cost
Image TipsPanel.currencyIcon
Referenced by SetDescription.
Sprite [] TipsPanel.currency
Referenced by SetDescription.
TextMeshProUGUI TipsPanel.name
TextMeshProUGUI TipsPanel.description
Transform TipsPanel.constraintsPanel
Referenced by SetDescription.
Transform TipsPanel.statsPanel
Referenced by SetDescription.
GameObject TipsPanel.statsBlockOriginal
Referenced by SetDescription.
TextMeshProUGUI TipsPanel.durability
Transform TipsPanel.actionButtonsPanel
Referenced by Show.
GameObject TipsPanel.actionButtonOriginal
Referenced by Show.
Vector2 TipsPanel.startSwipe
Referenced by OnBeginDrag, OnDrag.
Vector2 TipsPanel.startSwipePosition
Referenced by OnBeginDrag, OnDrag.
RectTransform TipsPanel.ThisTransform
Referenced by Awake, GetPosOnScreen, OnDrag, WaitForeRebuildPanel.
TipsPanel TipsPanel.Instance
Referenced by Awake.
bool TipsPanel.Showed
void TipsPanel.Awake()
References Instance, ThisTransform.
void TipsPanel.SetDescription(Description desc)
References Description.Constraints, constraintsPanel, Description.Cost, Description.CostCurrency, currency, currencyIcon, Description.Desc, Description.Durability, Description.Icon, StringFormats.intSeparatorNumber, Description.Name, StringFormats.nfi, Description.Stats, statsBlockOriginal, statsPanel.
Referenced by Show.
IEnumerator TipsPanel.WaitForeRebuildPanel(Vector2 worldPosOnScreen)
References GetPosOnScreen, ThisTransform.
Referenced by Show.
Vector3 TipsPanel.GetPosOnScreen(Vector2 worldPosOnScreen)
References ThisTransform.
Referenced by OnDrag, WaitForeRebuildPanel.
void TipsPanel.Show(Description desc, Vector2 worldPosOnScreen, List< Action > actions=null, List< string > actionsNames=null)
References actionButtonOriginal, actionButtonsPanel, SetDescription, WaitForeRebuildPanel.
void TipsPanel.Hide()
void TipsPanel.OnBeginDrag(PointerEventData eventData)
References startSwipe, startSwipePosition.
void TipsPanel.OnDrag(PointerEventData eventData)
References GetPosOnScreen, startSwipe, startSwipePosition, ThisTransform.