Toast
ToastLifetime
Toast Toast.Instance
Referenced by Awake.
TextMeshProUGUI Toast.text
float Toast.floatDuration
Referenced by Float, Show.
Vector2 Toast.floatShiftInPercent
Referenced by Show.
float Toast.startAlpha
Referenced by Float, Show.
CanvasGroup Toast.cg
Referenced by Awake.
new RectTransform Toast.transform
Referenced by Awake, WaitForRebuildPanel.
Coroutine Toast.lastCoroutine
Referenced by Hide, Show.
void Toast.Awake()
References cg, Hide, Instance, transform.
void Toast.Hide()
References lastCoroutine.
Referenced by Awake, Float, OnPointerClick, Show.
IEnumerator Toast.WaitForRebuildPanel()
References transform.
Referenced by Show.
IEnumerator Toast.Float(float floatDuration, float lifetime, Vector2 floatShiftInPercent, float startAlpha)
References floatDuration, Hide, startAlpha.
Referenced by Show.
void Toast.Show(string message, ToastLifetime lifetime=ToastLifetime.MEDIUM)
References Float, floatDuration, floatShiftInPercent, Hide, lastCoroutine, startAlpha, WaitForRebuildPanel.
void Toast.OnPointerClick(PointerEventData eventData)
References Hide.