MarketInventoryUI
GameObject MarketInventoryUI.inventoryItemOriginal
Referenced by SetImage.
Transform MarketInventoryUI.itemsContainer
Referenced by Awake.
bool MarketInventoryUI.autoFillMarket
Equipment [] MarketInventoryUI.originalEquipment
Referenced by AutiFill.
AnimationCurve MarketInventoryUI.dependanceOfGameLevel
int MarketInventoryUI.minLevel
int MarketInventoryUI.maxLevel
List<Transform> MarketInventoryUI.items
Referenced by AddToInventory, Awake, RefreshUI.
List<EquipmentStack> MarketInventoryUI.inventory
Referenced by AddToInventory, Awake, RefreshUI, RemoveFtomInventory.
bool MarketInventoryUI.Fill
Referenced by DropToEquipmentMarket.AddToThisInventory.
MarketInventoryUI MarketInventoryUI.Instance
Referenced by DropToEquipmentMarket.AddToThisInventory, Awake, ADropToMe.RefreshUI.
void MarketInventoryUI.Awake()
References Instance, inventory, items, itemsContainer.
void MarketInventoryUI.Start()
References AutiFill, RefreshUI.
void MarketInventoryUI.AutiFill()
References AddToInventory, Item.MainPropertie, originalEquipment.
Referenced by Start.
void MarketInventoryUI.AddToInventory(EquipmentStack stack)
References inventory, items.
Referenced by AutiFill.
void MarketInventoryUI.RemoveFtomInventory(EquipmentStack stack)
References inventory.
void MarketInventoryUI.RefreshUI()
References inventory, items, SetImage.
Referenced by Start.
void MarketInventoryUI.SetImage(Transform cell, EquipmentStack stack, bool canDrag)
References inventoryItemOriginal.
Referenced by RefreshUI.