SquadInventoryUI
SquadInventoryUI SquadInventoryUI.Instance
Referenced by Awake, ADropToMe.RefreshUI.
GameObject SquadInventoryUI.inventoryItemOriginal
Referenced by SetImage.
Transform SquadInventoryUI.helmetCell
Referenced by RefreshUI.
Transform SquadInventoryUI.bodyCell
Referenced by RefreshUI.
Transform SquadInventoryUI.shieldCell
Referenced by RefreshUI.
Transform SquadInventoryUI.weaponCell
Referenced by RefreshUI.
Transform [] SquadInventoryUI.inventoryCells
Referenced by RefreshUI.
Transform [] SquadInventoryUI.consumablesCells
ScorePanel SquadInventoryUI.scorePanel
bool SquadInventoryUI.canRefresh
Referenced by RefreshOnCntShanged, WaitForRefresh.
float SquadInventoryUI.timeToRefresh
Referenced by WaitForRefresh.
void SquadInventoryUI.Awake()
References Instance.
void SquadInventoryUI.Start()
References RefreshOnCntShanged, RefreshUI.
void SquadInventoryUI.OnDestroy()
References Squad.playerSquadInstance, RefreshOnCntShanged.
void SquadInventoryUI.RefreshOnCntShanged(int cnt)
References canRefresh, WaitForRefresh.
Referenced by OnDestroy, Start.
IEnumerator SquadInventoryUI.WaitForRefresh()
References canRefresh, RefreshUI, timeToRefresh.
Referenced by RefreshOnCntShanged.
void SquadInventoryUI.RefreshUI()
References Inventory.Body, bodyCell, EquipmentStats.Empty, Inventory.Helmet, helmetCell, Squad.Inventory, inventoryCells, Squad.playerSquadInstance, SetImage, Inventory.Shield, shieldCell, Equipment.Stats, Inventory.Weapon, weaponCell.
Referenced by Start, WaitForRefresh.
void SquadInventoryUI.SetImage(Transform cell, EquipmentStack stack, bool canDrag)
References inventoryItemOriginal.
Referenced by RefreshUI.