FormationButton
GameObject FormationButton.currentFormationButton
Image FormationButton.imageRanks
Image FormationButton.imagePhalanx
Image FormationButton.imageShields
Image FormationButton.thisImage
Referenced by Start.
CanvasGroup FormationButton.thisCg
Referenced by Start.
float FormationButton.angle
Referenced by OnDrag, OnPointerUp.
Vector2 FormationButton.startP
Referenced by GetAngle, OnDrag, OnPointerDown, OnPointerUp.
Vector2 FormationButton.endP
Referenced by GetAngle, OnDrag, OnPointerUp.
Transform FormationButton.thisTransform
Referenced by Start.
bool FormationButton.mouseDown
Referenced by OnDrag, OnPointerDown, OnPointerUp.
int FormationButton.touchId
Referenced by OnDrag, OnPointerDown, OnPointerUp.
bool FormationButton.canUse
Referenced by OnDrag, OnPointerDown, OnPointerUp, PlayerSquad_OnBeginCharge, PlayerSquad_OnEndCharge.
Squad FormationButton.playerSquad
Referenced by OnDestroy, OnPointerUp, PlayerSquadInstance_OnFormationChanged, Start.
void FormationButton.Start()
References Squad.CurrentFormation, playerSquad, PlayerSquad_OnBeginCharge, PlayerSquad_OnEndCharge, Squad.playerSquadInstance, PlayerSquadInstance_OnFormationChanged, SetButtonsEnabled, SetImage, thisCg, thisImage, thisTransform.
void FormationButton.OnDestroy()
References playerSquad, PlayerSquad_OnBeginCharge, PlayerSquad_OnEndCharge, PlayerSquadInstance_OnFormationChanged.
void FormationButton.PlayerSquad_OnBeginCharge(float addSpeed, float addAcceleration)
References canUse.
Referenced by OnDestroy, Start.
void FormationButton.PlayerSquad_OnEndCharge(float addSpeed, float addAcceleration)
References canUse.
Referenced by OnDestroy, Start.
void FormationButton.PlayerSquadInstance_OnFormationChanged(FormationStats.Formations formation)
References Squad.CurrentFormation, playerSquad, SetImage.
Referenced by OnDestroy, Start.
void FormationButton.SetImage(FormationStats.Formations formation)
Referenced by OnDrag, OnPointerUp, PlayerSquadInstance_OnFormationChanged, Start.
void FormationButton.SetButtonsEnabled(bool val)
Referenced by OnPointerDown, OnPointerUp, Start.
FormationStats.Formations FormationButton.GetFormation(float angle)
Referenced by OnDrag, OnPointerUp.
float FormationButton.GetAngle(Vector3 spart, Vector3 end)
References endP, startP.
Referenced by OnDrag, OnPointerUp.
void FormationButton.OnPointerDown(PointerEventData eventData)
References canUse, mouseDown, SetButtonsEnabled, startP, touchId.
void FormationButton.OnPointerUp(PointerEventData eventData)
References angle, canUse, Squad.CurrentFormation, endP, GetAngle, GetFormation, mouseDown, playerSquad, SetButtonsEnabled, SetImage, startP, touchId.
void FormationButton.OnDrag(PointerEventData eventData)
References angle, canUse, endP, GetAngle, GetFormation, mouseDown, SetImage, startP, touchId.